/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for BotProfileObject type.
 */
public class BotProfileObject {
    private String appId;
    private boolean deleted;
    private Icons icons;
    private String id;
    private String name;
    private String teamId;
    private int updated;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public BotProfileObject() {
    }

    /**
     * Initialization constructor.
     * @param  appId  String value for appId.
     * @param  deleted  boolean value for deleted.
     * @param  icons  Icons value for icons.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  teamId  String value for teamId.
     * @param  updated  int value for updated.
     */
    public BotProfileObject(
            String appId,
            boolean deleted,
            Icons icons,
            String id,
            String name,
            String teamId,
            int updated) {
        this.appId = appId;
        this.deleted = deleted;
        this.icons = icons;
        this.id = id;
        this.name = name;
        this.teamId = teamId;
        this.updated = updated;
    }

    /**
     * Getter for AppId.
     * @return Returns the String
     */
    @JsonGetter("app_id")
    public String getAppId() {
        return appId;
    }

    /**
     * Setter for AppId.
     * @param appId Value for String
     */
    @JsonSetter("app_id")
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * Getter for Deleted.
     * @return Returns the boolean
     */
    @JsonGetter("deleted")
    public boolean getDeleted() {
        return deleted;
    }

    /**
     * Setter for Deleted.
     * @param deleted Value for boolean
     */
    @JsonSetter("deleted")
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Getter for Icons.
     * @return Returns the Icons
     */
    @JsonGetter("icons")
    public Icons getIcons() {
        return icons;
    }

    /**
     * Setter for Icons.
     * @param icons Value for Icons
     */
    @JsonSetter("icons")
    public void setIcons(Icons icons) {
        this.icons = icons;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for TeamId.
     * @return Returns the String
     */
    @JsonGetter("team_id")
    public String getTeamId() {
        return teamId;
    }

    /**
     * Setter for TeamId.
     * @param teamId Value for String
     */
    @JsonSetter("team_id")
    public void setTeamId(String teamId) {
        this.teamId = teamId;
    }

    /**
     * Getter for Updated.
     * @return Returns the int
     */
    @JsonGetter("updated")
    public int getUpdated() {
        return updated;
    }

    /**
     * Setter for Updated.
     * @param updated Value for int
     */
    @JsonSetter("updated")
    public void setUpdated(int updated) {
        this.updated = updated;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this BotProfileObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BotProfileObject [" + "appId=" + appId + ", deleted=" + deleted + ", icons=" + icons
                + ", id=" + id + ", name=" + name + ", teamId=" + teamId + ", updated=" + updated
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link BotProfileObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BotProfileObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(appId, deleted, icons, id, name, teamId, updated);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link BotProfileObject}.
     */
    public static class Builder {
        private String appId;
        private boolean deleted;
        private Icons icons;
        private String id;
        private String name;
        private String teamId;
        private int updated;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  appId  String value for appId.
         * @param  deleted  boolean value for deleted.
         * @param  icons  Icons value for icons.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  teamId  String value for teamId.
         * @param  updated  int value for updated.
         */
        public Builder(String appId, boolean deleted, Icons icons, String id, String name,
                String teamId, int updated) {
            this.appId = appId;
            this.deleted = deleted;
            this.icons = icons;
            this.id = id;
            this.name = name;
            this.teamId = teamId;
            this.updated = updated;
        }

        /**
         * Setter for appId.
         * @param  appId  String value for appId.
         * @return Builder
         */
        public Builder appId(String appId) {
            this.appId = appId;
            return this;
        }

        /**
         * Setter for deleted.
         * @param  deleted  boolean value for deleted.
         * @return Builder
         */
        public Builder deleted(boolean deleted) {
            this.deleted = deleted;
            return this;
        }

        /**
         * Setter for icons.
         * @param  icons  Icons value for icons.
         * @return Builder
         */
        public Builder icons(Icons icons) {
            this.icons = icons;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for teamId.
         * @param  teamId  String value for teamId.
         * @return Builder
         */
        public Builder teamId(String teamId) {
            this.teamId = teamId;
            return this;
        }

        /**
         * Setter for updated.
         * @param  updated  int value for updated.
         * @return Builder
         */
        public Builder updated(int updated) {
            this.updated = updated;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link BotProfileObject} object using the set fields.
         * @return {@link BotProfileObject}
         */
        public BotProfileObject build() {
            BotProfileObject model =
                    new BotProfileObject(appId, deleted, icons, id, name, teamId, updated);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
