/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ChannelObject type.
 */
public class ChannelObject {
    private String acceptedUser;
    private int created;
    private String creator;
    private String id;
    private Boolean isArchived;
    private boolean isChannel;
    private Boolean isFrozen;
    private Boolean isGeneral;
    private Boolean isMember;
    private Integer isMoved;
    private boolean isMpim;
    private Boolean isNonThreadable;
    private boolean isOrgShared;
    private Boolean isPendingExtShared;
    private boolean isPrivate;
    private Boolean isReadOnly;
    private boolean isShared;
    private Boolean isThreadOnly;
    private String lastRead;
    private Object latest;
    private List<String> members;
    private String name;
    private String nameNormalized;
    private Integer numMembers;
    private List<String> pendingShared;
    private List<String> previousNames;
    private Double priority;
    private Purpose purpose;
    private Topic topic;
    private Integer unlinked;
    private Integer unreadCount;
    private Integer unreadCountDisplay;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ChannelObject() {
    }

    /**
     * Initialization constructor.
     * @param  created  int value for created.
     * @param  creator  String value for creator.
     * @param  id  String value for id.
     * @param  isChannel  boolean value for isChannel.
     * @param  isMpim  boolean value for isMpim.
     * @param  isOrgShared  boolean value for isOrgShared.
     * @param  isPrivate  boolean value for isPrivate.
     * @param  isShared  boolean value for isShared.
     * @param  members  List of String value for members.
     * @param  name  String value for name.
     * @param  nameNormalized  String value for nameNormalized.
     * @param  purpose  Purpose value for purpose.
     * @param  topic  Topic value for topic.
     * @param  acceptedUser  String value for acceptedUser.
     * @param  isArchived  Boolean value for isArchived.
     * @param  isFrozen  Boolean value for isFrozen.
     * @param  isGeneral  Boolean value for isGeneral.
     * @param  isMember  Boolean value for isMember.
     * @param  isMoved  Integer value for isMoved.
     * @param  isNonThreadable  Boolean value for isNonThreadable.
     * @param  isPendingExtShared  Boolean value for isPendingExtShared.
     * @param  isReadOnly  Boolean value for isReadOnly.
     * @param  isThreadOnly  Boolean value for isThreadOnly.
     * @param  lastRead  String value for lastRead.
     * @param  latest  Object value for latest.
     * @param  numMembers  Integer value for numMembers.
     * @param  pendingShared  List of String value for pendingShared.
     * @param  previousNames  List of String value for previousNames.
     * @param  priority  Double value for priority.
     * @param  unlinked  Integer value for unlinked.
     * @param  unreadCount  Integer value for unreadCount.
     * @param  unreadCountDisplay  Integer value for unreadCountDisplay.
     */
    public ChannelObject(
            int created,
            String creator,
            String id,
            boolean isChannel,
            boolean isMpim,
            boolean isOrgShared,
            boolean isPrivate,
            boolean isShared,
            List<String> members,
            String name,
            String nameNormalized,
            Purpose purpose,
            Topic topic,
            String acceptedUser,
            Boolean isArchived,
            Boolean isFrozen,
            Boolean isGeneral,
            Boolean isMember,
            Integer isMoved,
            Boolean isNonThreadable,
            Boolean isPendingExtShared,
            Boolean isReadOnly,
            Boolean isThreadOnly,
            String lastRead,
            Object latest,
            Integer numMembers,
            List<String> pendingShared,
            List<String> previousNames,
            Double priority,
            Integer unlinked,
            Integer unreadCount,
            Integer unreadCountDisplay) {
        this.acceptedUser = acceptedUser;
        this.created = created;
        this.creator = creator;
        this.id = id;
        this.isArchived = isArchived;
        this.isChannel = isChannel;
        this.isFrozen = isFrozen;
        this.isGeneral = isGeneral;
        this.isMember = isMember;
        this.isMoved = isMoved;
        this.isMpim = isMpim;
        this.isNonThreadable = isNonThreadable;
        this.isOrgShared = isOrgShared;
        this.isPendingExtShared = isPendingExtShared;
        this.isPrivate = isPrivate;
        this.isReadOnly = isReadOnly;
        this.isShared = isShared;
        this.isThreadOnly = isThreadOnly;
        this.lastRead = lastRead;
        this.latest = latest;
        this.members = members;
        this.name = name;
        this.nameNormalized = nameNormalized;
        this.numMembers = numMembers;
        this.pendingShared = pendingShared;
        this.previousNames = previousNames;
        this.priority = priority;
        this.purpose = purpose;
        this.topic = topic;
        this.unlinked = unlinked;
        this.unreadCount = unreadCount;
        this.unreadCountDisplay = unreadCountDisplay;
    }

    /**
     * Getter for AcceptedUser.
     * @return Returns the String
     */
    @JsonGetter("accepted_user")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAcceptedUser() {
        return acceptedUser;
    }

    /**
     * Setter for AcceptedUser.
     * @param acceptedUser Value for String
     */
    @JsonSetter("accepted_user")
    public void setAcceptedUser(String acceptedUser) {
        this.acceptedUser = acceptedUser;
    }

    /**
     * Getter for Created.
     * @return Returns the int
     */
    @JsonGetter("created")
    public int getCreated() {
        return created;
    }

    /**
     * Setter for Created.
     * @param created Value for int
     */
    @JsonSetter("created")
    public void setCreated(int created) {
        this.created = created;
    }

    /**
     * Getter for Creator.
     * @return Returns the String
     */
    @JsonGetter("creator")
    public String getCreator() {
        return creator;
    }

    /**
     * Setter for Creator.
     * @param creator Value for String
     */
    @JsonSetter("creator")
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for IsArchived.
     * @return Returns the Boolean
     */
    @JsonGetter("is_archived")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsArchived() {
        return isArchived;
    }

    /**
     * Setter for IsArchived.
     * @param isArchived Value for Boolean
     */
    @JsonSetter("is_archived")
    public void setIsArchived(Boolean isArchived) {
        this.isArchived = isArchived;
    }

    /**
     * Getter for IsChannel.
     * @return Returns the boolean
     */
    @JsonGetter("is_channel")
    public boolean getIsChannel() {
        return isChannel;
    }

    /**
     * Setter for IsChannel.
     * @param isChannel Value for boolean
     */
    @JsonSetter("is_channel")
    public void setIsChannel(boolean isChannel) {
        this.isChannel = isChannel;
    }

    /**
     * Getter for IsFrozen.
     * @return Returns the Boolean
     */
    @JsonGetter("is_frozen")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsFrozen() {
        return isFrozen;
    }

    /**
     * Setter for IsFrozen.
     * @param isFrozen Value for Boolean
     */
    @JsonSetter("is_frozen")
    public void setIsFrozen(Boolean isFrozen) {
        this.isFrozen = isFrozen;
    }

    /**
     * Getter for IsGeneral.
     * @return Returns the Boolean
     */
    @JsonGetter("is_general")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsGeneral() {
        return isGeneral;
    }

    /**
     * Setter for IsGeneral.
     * @param isGeneral Value for Boolean
     */
    @JsonSetter("is_general")
    public void setIsGeneral(Boolean isGeneral) {
        this.isGeneral = isGeneral;
    }

    /**
     * Getter for IsMember.
     * @return Returns the Boolean
     */
    @JsonGetter("is_member")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsMember() {
        return isMember;
    }

    /**
     * Setter for IsMember.
     * @param isMember Value for Boolean
     */
    @JsonSetter("is_member")
    public void setIsMember(Boolean isMember) {
        this.isMember = isMember;
    }

    /**
     * Getter for IsMoved.
     * @return Returns the Integer
     */
    @JsonGetter("is_moved")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getIsMoved() {
        return isMoved;
    }

    /**
     * Setter for IsMoved.
     * @param isMoved Value for Integer
     */
    @JsonSetter("is_moved")
    public void setIsMoved(Integer isMoved) {
        this.isMoved = isMoved;
    }

    /**
     * Getter for IsMpim.
     * @return Returns the boolean
     */
    @JsonGetter("is_mpim")
    public boolean getIsMpim() {
        return isMpim;
    }

    /**
     * Setter for IsMpim.
     * @param isMpim Value for boolean
     */
    @JsonSetter("is_mpim")
    public void setIsMpim(boolean isMpim) {
        this.isMpim = isMpim;
    }

    /**
     * Getter for IsNonThreadable.
     * @return Returns the Boolean
     */
    @JsonGetter("is_non_threadable")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsNonThreadable() {
        return isNonThreadable;
    }

    /**
     * Setter for IsNonThreadable.
     * @param isNonThreadable Value for Boolean
     */
    @JsonSetter("is_non_threadable")
    public void setIsNonThreadable(Boolean isNonThreadable) {
        this.isNonThreadable = isNonThreadable;
    }

    /**
     * Getter for IsOrgShared.
     * @return Returns the boolean
     */
    @JsonGetter("is_org_shared")
    public boolean getIsOrgShared() {
        return isOrgShared;
    }

    /**
     * Setter for IsOrgShared.
     * @param isOrgShared Value for boolean
     */
    @JsonSetter("is_org_shared")
    public void setIsOrgShared(boolean isOrgShared) {
        this.isOrgShared = isOrgShared;
    }

    /**
     * Getter for IsPendingExtShared.
     * @return Returns the Boolean
     */
    @JsonGetter("is_pending_ext_shared")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsPendingExtShared() {
        return isPendingExtShared;
    }

    /**
     * Setter for IsPendingExtShared.
     * @param isPendingExtShared Value for Boolean
     */
    @JsonSetter("is_pending_ext_shared")
    public void setIsPendingExtShared(Boolean isPendingExtShared) {
        this.isPendingExtShared = isPendingExtShared;
    }

    /**
     * Getter for IsPrivate.
     * @return Returns the boolean
     */
    @JsonGetter("is_private")
    public boolean getIsPrivate() {
        return isPrivate;
    }

    /**
     * Setter for IsPrivate.
     * @param isPrivate Value for boolean
     */
    @JsonSetter("is_private")
    public void setIsPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * Getter for IsReadOnly.
     * @return Returns the Boolean
     */
    @JsonGetter("is_read_only")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsReadOnly() {
        return isReadOnly;
    }

    /**
     * Setter for IsReadOnly.
     * @param isReadOnly Value for Boolean
     */
    @JsonSetter("is_read_only")
    public void setIsReadOnly(Boolean isReadOnly) {
        this.isReadOnly = isReadOnly;
    }

    /**
     * Getter for IsShared.
     * @return Returns the boolean
     */
    @JsonGetter("is_shared")
    public boolean getIsShared() {
        return isShared;
    }

    /**
     * Setter for IsShared.
     * @param isShared Value for boolean
     */
    @JsonSetter("is_shared")
    public void setIsShared(boolean isShared) {
        this.isShared = isShared;
    }

    /**
     * Getter for IsThreadOnly.
     * @return Returns the Boolean
     */
    @JsonGetter("is_thread_only")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsThreadOnly() {
        return isThreadOnly;
    }

    /**
     * Setter for IsThreadOnly.
     * @param isThreadOnly Value for Boolean
     */
    @JsonSetter("is_thread_only")
    public void setIsThreadOnly(Boolean isThreadOnly) {
        this.isThreadOnly = isThreadOnly;
    }

    /**
     * Getter for LastRead.
     * @return Returns the String
     */
    @JsonGetter("last_read")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastRead() {
        return lastRead;
    }

    /**
     * Setter for LastRead.
     * @param lastRead Value for String
     */
    @JsonSetter("last_read")
    public void setLastRead(String lastRead) {
        this.lastRead = lastRead;
    }

    /**
     * Getter for Latest.
     * @return Returns the Object
     */
    @JsonGetter("latest")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getLatest() {
        return latest;
    }

    /**
     * Setter for Latest.
     * @param latest Value for Object
     */
    @JsonSetter("latest")
    public void setLatest(Object latest) {
        this.latest = latest;
    }

    /**
     * Getter for Members.
     * @return Returns the List of String
     */
    @JsonGetter("members")
    public List<String> getMembers() {
        return members;
    }

    /**
     * Setter for Members.
     * @param members Value for List of String
     */
    @JsonSetter("members")
    public void setMembers(List<String> members) {
        this.members = members;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for NameNormalized.
     * @return Returns the String
     */
    @JsonGetter("name_normalized")
    public String getNameNormalized() {
        return nameNormalized;
    }

    /**
     * Setter for NameNormalized.
     * @param nameNormalized Value for String
     */
    @JsonSetter("name_normalized")
    public void setNameNormalized(String nameNormalized) {
        this.nameNormalized = nameNormalized;
    }

    /**
     * Getter for NumMembers.
     * @return Returns the Integer
     */
    @JsonGetter("num_members")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumMembers() {
        return numMembers;
    }

    /**
     * Setter for NumMembers.
     * @param numMembers Value for Integer
     */
    @JsonSetter("num_members")
    public void setNumMembers(Integer numMembers) {
        this.numMembers = numMembers;
    }

    /**
     * Getter for PendingShared.
     * @return Returns the List of String
     */
    @JsonGetter("pending_shared")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPendingShared() {
        return pendingShared;
    }

    /**
     * Setter for PendingShared.
     * @param pendingShared Value for List of String
     */
    @JsonSetter("pending_shared")
    public void setPendingShared(List<String> pendingShared) {
        this.pendingShared = pendingShared;
    }

    /**
     * Getter for PreviousNames.
     * @return Returns the List of String
     */
    @JsonGetter("previous_names")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPreviousNames() {
        return previousNames;
    }

    /**
     * Setter for PreviousNames.
     * @param previousNames Value for List of String
     */
    @JsonSetter("previous_names")
    public void setPreviousNames(List<String> previousNames) {
        this.previousNames = previousNames;
    }

    /**
     * Getter for Priority.
     * @return Returns the Double
     */
    @JsonGetter("priority")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriority() {
        return priority;
    }

    /**
     * Setter for Priority.
     * @param priority Value for Double
     */
    @JsonSetter("priority")
    public void setPriority(Double priority) {
        this.priority = priority;
    }

    /**
     * Getter for Purpose.
     * @return Returns the Purpose
     */
    @JsonGetter("purpose")
    public Purpose getPurpose() {
        return purpose;
    }

    /**
     * Setter for Purpose.
     * @param purpose Value for Purpose
     */
    @JsonSetter("purpose")
    public void setPurpose(Purpose purpose) {
        this.purpose = purpose;
    }

    /**
     * Getter for Topic.
     * @return Returns the Topic
     */
    @JsonGetter("topic")
    public Topic getTopic() {
        return topic;
    }

    /**
     * Setter for Topic.
     * @param topic Value for Topic
     */
    @JsonSetter("topic")
    public void setTopic(Topic topic) {
        this.topic = topic;
    }

    /**
     * Getter for Unlinked.
     * @return Returns the Integer
     */
    @JsonGetter("unlinked")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnlinked() {
        return unlinked;
    }

    /**
     * Setter for Unlinked.
     * @param unlinked Value for Integer
     */
    @JsonSetter("unlinked")
    public void setUnlinked(Integer unlinked) {
        this.unlinked = unlinked;
    }

    /**
     * Getter for UnreadCount.
     * @return Returns the Integer
     */
    @JsonGetter("unread_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnreadCount() {
        return unreadCount;
    }

    /**
     * Setter for UnreadCount.
     * @param unreadCount Value for Integer
     */
    @JsonSetter("unread_count")
    public void setUnreadCount(Integer unreadCount) {
        this.unreadCount = unreadCount;
    }

    /**
     * Getter for UnreadCountDisplay.
     * @return Returns the Integer
     */
    @JsonGetter("unread_count_display")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnreadCountDisplay() {
        return unreadCountDisplay;
    }

    /**
     * Setter for UnreadCountDisplay.
     * @param unreadCountDisplay Value for Integer
     */
    @JsonSetter("unread_count_display")
    public void setUnreadCountDisplay(Integer unreadCountDisplay) {
        this.unreadCountDisplay = unreadCountDisplay;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ChannelObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChannelObject [" + "created=" + created + ", creator=" + creator + ", id=" + id
                + ", isChannel=" + isChannel + ", isMpim=" + isMpim + ", isOrgShared=" + isOrgShared
                + ", isPrivate=" + isPrivate + ", isShared=" + isShared + ", members=" + members
                + ", name=" + name + ", nameNormalized=" + nameNormalized + ", purpose=" + purpose
                + ", topic=" + topic + ", acceptedUser=" + acceptedUser + ", isArchived="
                + isArchived + ", isFrozen=" + isFrozen + ", isGeneral=" + isGeneral + ", isMember="
                + isMember + ", isMoved=" + isMoved + ", isNonThreadable=" + isNonThreadable
                + ", isPendingExtShared=" + isPendingExtShared + ", isReadOnly=" + isReadOnly
                + ", isThreadOnly=" + isThreadOnly + ", lastRead=" + lastRead + ", latest=" + latest
                + ", numMembers=" + numMembers + ", pendingShared=" + pendingShared
                + ", previousNames=" + previousNames + ", priority=" + priority + ", unlinked="
                + unlinked + ", unreadCount=" + unreadCount + ", unreadCountDisplay="
                + unreadCountDisplay + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ChannelObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChannelObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(created, creator, id, isChannel, isMpim, isOrgShared,
                isPrivate, isShared, members, name, nameNormalized, purpose, topic)
                .acceptedUser(getAcceptedUser())
                .isArchived(getIsArchived())
                .isFrozen(getIsFrozen())
                .isGeneral(getIsGeneral())
                .isMember(getIsMember())
                .isMoved(getIsMoved())
                .isNonThreadable(getIsNonThreadable())
                .isPendingExtShared(getIsPendingExtShared())
                .isReadOnly(getIsReadOnly())
                .isThreadOnly(getIsThreadOnly())
                .lastRead(getLastRead())
                .latest(getLatest())
                .numMembers(getNumMembers())
                .pendingShared(getPendingShared())
                .previousNames(getPreviousNames())
                .priority(getPriority())
                .unlinked(getUnlinked())
                .unreadCount(getUnreadCount())
                .unreadCountDisplay(getUnreadCountDisplay());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ChannelObject}.
     */
    public static class Builder {
        private int created;
        private String creator;
        private String id;
        private boolean isChannel;
        private boolean isMpim;
        private boolean isOrgShared;
        private boolean isPrivate;
        private boolean isShared;
        private List<String> members;
        private String name;
        private String nameNormalized;
        private Purpose purpose;
        private Topic topic;
        private String acceptedUser;
        private Boolean isArchived;
        private Boolean isFrozen;
        private Boolean isGeneral;
        private Boolean isMember;
        private Integer isMoved;
        private Boolean isNonThreadable;
        private Boolean isPendingExtShared;
        private Boolean isReadOnly;
        private Boolean isThreadOnly;
        private String lastRead;
        private Object latest;
        private Integer numMembers;
        private List<String> pendingShared;
        private List<String> previousNames;
        private Double priority;
        private Integer unlinked;
        private Integer unreadCount;
        private Integer unreadCountDisplay;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  created  int value for created.
         * @param  creator  String value for creator.
         * @param  id  String value for id.
         * @param  isChannel  boolean value for isChannel.
         * @param  isMpim  boolean value for isMpim.
         * @param  isOrgShared  boolean value for isOrgShared.
         * @param  isPrivate  boolean value for isPrivate.
         * @param  isShared  boolean value for isShared.
         * @param  members  List of String value for members.
         * @param  name  String value for name.
         * @param  nameNormalized  String value for nameNormalized.
         * @param  purpose  Purpose value for purpose.
         * @param  topic  Topic value for topic.
         */
        public Builder(int created, String creator, String id, boolean isChannel, boolean isMpim,
                boolean isOrgShared, boolean isPrivate, boolean isShared, List<String> members,
                String name, String nameNormalized, Purpose purpose, Topic topic) {
            this.created = created;
            this.creator = creator;
            this.id = id;
            this.isChannel = isChannel;
            this.isMpim = isMpim;
            this.isOrgShared = isOrgShared;
            this.isPrivate = isPrivate;
            this.isShared = isShared;
            this.members = members;
            this.name = name;
            this.nameNormalized = nameNormalized;
            this.purpose = purpose;
            this.topic = topic;
        }

        /**
         * Setter for created.
         * @param  created  int value for created.
         * @return Builder
         */
        public Builder created(int created) {
            this.created = created;
            return this;
        }

        /**
         * Setter for creator.
         * @param  creator  String value for creator.
         * @return Builder
         */
        public Builder creator(String creator) {
            this.creator = creator;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for isChannel.
         * @param  isChannel  boolean value for isChannel.
         * @return Builder
         */
        public Builder isChannel(boolean isChannel) {
            this.isChannel = isChannel;
            return this;
        }

        /**
         * Setter for isMpim.
         * @param  isMpim  boolean value for isMpim.
         * @return Builder
         */
        public Builder isMpim(boolean isMpim) {
            this.isMpim = isMpim;
            return this;
        }

        /**
         * Setter for isOrgShared.
         * @param  isOrgShared  boolean value for isOrgShared.
         * @return Builder
         */
        public Builder isOrgShared(boolean isOrgShared) {
            this.isOrgShared = isOrgShared;
            return this;
        }

        /**
         * Setter for isPrivate.
         * @param  isPrivate  boolean value for isPrivate.
         * @return Builder
         */
        public Builder isPrivate(boolean isPrivate) {
            this.isPrivate = isPrivate;
            return this;
        }

        /**
         * Setter for isShared.
         * @param  isShared  boolean value for isShared.
         * @return Builder
         */
        public Builder isShared(boolean isShared) {
            this.isShared = isShared;
            return this;
        }

        /**
         * Setter for members.
         * @param  members  List of String value for members.
         * @return Builder
         */
        public Builder members(List<String> members) {
            this.members = members;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for nameNormalized.
         * @param  nameNormalized  String value for nameNormalized.
         * @return Builder
         */
        public Builder nameNormalized(String nameNormalized) {
            this.nameNormalized = nameNormalized;
            return this;
        }

        /**
         * Setter for purpose.
         * @param  purpose  Purpose value for purpose.
         * @return Builder
         */
        public Builder purpose(Purpose purpose) {
            this.purpose = purpose;
            return this;
        }

        /**
         * Setter for topic.
         * @param  topic  Topic value for topic.
         * @return Builder
         */
        public Builder topic(Topic topic) {
            this.topic = topic;
            return this;
        }

        /**
         * Setter for acceptedUser.
         * @param  acceptedUser  String value for acceptedUser.
         * @return Builder
         */
        public Builder acceptedUser(String acceptedUser) {
            this.acceptedUser = acceptedUser;
            return this;
        }

        /**
         * Setter for isArchived.
         * @param  isArchived  Boolean value for isArchived.
         * @return Builder
         */
        public Builder isArchived(Boolean isArchived) {
            this.isArchived = isArchived;
            return this;
        }

        /**
         * Setter for isFrozen.
         * @param  isFrozen  Boolean value for isFrozen.
         * @return Builder
         */
        public Builder isFrozen(Boolean isFrozen) {
            this.isFrozen = isFrozen;
            return this;
        }

        /**
         * Setter for isGeneral.
         * @param  isGeneral  Boolean value for isGeneral.
         * @return Builder
         */
        public Builder isGeneral(Boolean isGeneral) {
            this.isGeneral = isGeneral;
            return this;
        }

        /**
         * Setter for isMember.
         * @param  isMember  Boolean value for isMember.
         * @return Builder
         */
        public Builder isMember(Boolean isMember) {
            this.isMember = isMember;
            return this;
        }

        /**
         * Setter for isMoved.
         * @param  isMoved  Integer value for isMoved.
         * @return Builder
         */
        public Builder isMoved(Integer isMoved) {
            this.isMoved = isMoved;
            return this;
        }

        /**
         * Setter for isNonThreadable.
         * @param  isNonThreadable  Boolean value for isNonThreadable.
         * @return Builder
         */
        public Builder isNonThreadable(Boolean isNonThreadable) {
            this.isNonThreadable = isNonThreadable;
            return this;
        }

        /**
         * Setter for isPendingExtShared.
         * @param  isPendingExtShared  Boolean value for isPendingExtShared.
         * @return Builder
         */
        public Builder isPendingExtShared(Boolean isPendingExtShared) {
            this.isPendingExtShared = isPendingExtShared;
            return this;
        }

        /**
         * Setter for isReadOnly.
         * @param  isReadOnly  Boolean value for isReadOnly.
         * @return Builder
         */
        public Builder isReadOnly(Boolean isReadOnly) {
            this.isReadOnly = isReadOnly;
            return this;
        }

        /**
         * Setter for isThreadOnly.
         * @param  isThreadOnly  Boolean value for isThreadOnly.
         * @return Builder
         */
        public Builder isThreadOnly(Boolean isThreadOnly) {
            this.isThreadOnly = isThreadOnly;
            return this;
        }

        /**
         * Setter for lastRead.
         * @param  lastRead  String value for lastRead.
         * @return Builder
         */
        public Builder lastRead(String lastRead) {
            this.lastRead = lastRead;
            return this;
        }

        /**
         * Setter for latest.
         * @param  latest  Object value for latest.
         * @return Builder
         */
        public Builder latest(Object latest) {
            this.latest = latest;
            return this;
        }

        /**
         * Setter for numMembers.
         * @param  numMembers  Integer value for numMembers.
         * @return Builder
         */
        public Builder numMembers(Integer numMembers) {
            this.numMembers = numMembers;
            return this;
        }

        /**
         * Setter for pendingShared.
         * @param  pendingShared  List of String value for pendingShared.
         * @return Builder
         */
        public Builder pendingShared(List<String> pendingShared) {
            this.pendingShared = pendingShared;
            return this;
        }

        /**
         * Setter for previousNames.
         * @param  previousNames  List of String value for previousNames.
         * @return Builder
         */
        public Builder previousNames(List<String> previousNames) {
            this.previousNames = previousNames;
            return this;
        }

        /**
         * Setter for priority.
         * @param  priority  Double value for priority.
         * @return Builder
         */
        public Builder priority(Double priority) {
            this.priority = priority;
            return this;
        }

        /**
         * Setter for unlinked.
         * @param  unlinked  Integer value for unlinked.
         * @return Builder
         */
        public Builder unlinked(Integer unlinked) {
            this.unlinked = unlinked;
            return this;
        }

        /**
         * Setter for unreadCount.
         * @param  unreadCount  Integer value for unreadCount.
         * @return Builder
         */
        public Builder unreadCount(Integer unreadCount) {
            this.unreadCount = unreadCount;
            return this;
        }

        /**
         * Setter for unreadCountDisplay.
         * @param  unreadCountDisplay  Integer value for unreadCountDisplay.
         * @return Builder
         */
        public Builder unreadCountDisplay(Integer unreadCountDisplay) {
            this.unreadCountDisplay = unreadCountDisplay;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ChannelObject} object using the set fields.
         * @return {@link ChannelObject}
         */
        public ChannelObject build() {
            ChannelObject model =
                    new ChannelObject(created, creator, id, isChannel, isMpim, isOrgShared,
                            isPrivate, isShared, members, name, nameNormalized, purpose, topic,
                            acceptedUser, isArchived, isFrozen, isGeneral, isMember, isMoved,
                            isNonThreadable, isPendingExtShared, isReadOnly, isThreadOnly, lastRead,
                            latest, numMembers, pendingShared, previousNames, priority, unlinked,
                            unreadCount, unreadCountDisplay);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
