/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ChatGetPermalinkSuccessSchema type.
 */
public class ChatGetPermalinkSuccessSchema {
    private String channel;
    private String ok;
    private String permalink;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ChatGetPermalinkSuccessSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  channel  String value for channel.
     * @param  ok  String value for ok.
     * @param  permalink  String value for permalink.
     */
    public ChatGetPermalinkSuccessSchema(
            String channel,
            String ok,
            String permalink) {
        this.channel = channel;
        this.ok = ok;
        this.permalink = permalink;
    }

    /**
     * Getter for Channel.
     * @return Returns the String
     */
    @JsonGetter("channel")
    public String getChannel() {
        return channel;
    }

    /**
     * Setter for Channel.
     * @param channel Value for String
     */
    @JsonSetter("channel")
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Permalink.
     * @return Returns the String
     */
    @JsonGetter("permalink")
    public String getPermalink() {
        return permalink;
    }

    /**
     * Setter for Permalink.
     * @param permalink Value for String
     */
    @JsonSetter("permalink")
    public void setPermalink(String permalink) {
        this.permalink = permalink;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ChatGetPermalinkSuccessSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChatGetPermalinkSuccessSchema [" + "channel=" + channel + ", ok=" + ok
                + ", permalink=" + permalink + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ChatGetPermalinkSuccessSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChatGetPermalinkSuccessSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(channel, ok, permalink);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ChatGetPermalinkSuccessSchema}.
     */
    public static class Builder {
        private String channel;
        private String ok = "True";
        private String permalink;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  channel  String value for channel.
         * @param  ok  String value for ok.
         * @param  permalink  String value for permalink.
         */
        public Builder(String channel, String ok, String permalink) {
            this.channel = channel;
            this.ok = ok;
            this.permalink = permalink;
        }

        /**
         * Setter for channel.
         * @param  channel  String value for channel.
         * @return Builder
         */
        public Builder channel(String channel) {
            this.channel = channel;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for permalink.
         * @param  permalink  String value for permalink.
         * @return Builder
         */
        public Builder permalink(String permalink) {
            this.permalink = permalink;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ChatGetPermalinkSuccessSchema} object using the set fields.
         * @return {@link ChatGetPermalinkSuccessSchema}
         */
        public ChatGetPermalinkSuccessSchema build() {
            ChatGetPermalinkSuccessSchema model =
                    new ChatGetPermalinkSuccessSchema(channel, ok, permalink);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
