/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ChatDeleteSuccessSchema type.
 */
public class ChatDeleteSuccessSchema {
    private String channel;
    private String ok;
    private String ts;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ChatDeleteSuccessSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  channel  String value for channel.
     * @param  ok  String value for ok.
     * @param  ts  String value for ts.
     */
    public ChatDeleteSuccessSchema(
            String channel,
            String ok,
            String ts) {
        this.channel = channel;
        this.ok = ok;
        this.ts = ts;
    }

    /**
     * Getter for Channel.
     * @return Returns the String
     */
    @JsonGetter("channel")
    public String getChannel() {
        return channel;
    }

    /**
     * Setter for Channel.
     * @param channel Value for String
     */
    @JsonSetter("channel")
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Ts.
     * @return Returns the String
     */
    @JsonGetter("ts")
    public String getTs() {
        return ts;
    }

    /**
     * Setter for Ts.
     * @param ts Value for String
     */
    @JsonSetter("ts")
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ChatDeleteSuccessSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChatDeleteSuccessSchema [" + "channel=" + channel + ", ok=" + ok + ", ts=" + ts
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ChatDeleteSuccessSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChatDeleteSuccessSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(channel, ok, ts);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ChatDeleteSuccessSchema}.
     */
    public static class Builder {
        private String channel;
        private String ok = "True";
        private String ts;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  channel  String value for channel.
         * @param  ok  String value for ok.
         * @param  ts  String value for ts.
         */
        public Builder(String channel, String ok, String ts) {
            this.channel = channel;
            this.ok = ok;
            this.ts = ts;
        }

        /**
         * Setter for channel.
         * @param  channel  String value for channel.
         * @return Builder
         */
        public Builder channel(String channel) {
            this.channel = channel;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for ts.
         * @param  ts  String value for ts.
         * @return Builder
         */
        public Builder ts(String ts) {
            this.ts = ts;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ChatDeleteSuccessSchema} object using the set fields.
         * @return {@link ChatDeleteSuccessSchema}
         */
        public ChatDeleteSuccessSchema build() {
            ChatDeleteSuccessSchema model =
                    new ChatDeleteSuccessSchema(channel, ok, ts);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
