/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ChatUpdateSuccessSchema type.
 */
public class ChatUpdateSuccessSchema {
    private String channel;
    private MessageObject1 message;
    private String ok;
    private String text;
    private String ts;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ChatUpdateSuccessSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  channel  String value for channel.
     * @param  message  MessageObject1 value for message.
     * @param  ok  String value for ok.
     * @param  text  String value for text.
     * @param  ts  String value for ts.
     */
    public ChatUpdateSuccessSchema(
            String channel,
            MessageObject1 message,
            String ok,
            String text,
            String ts) {
        this.channel = channel;
        this.message = message;
        this.ok = ok;
        this.text = text;
        this.ts = ts;
    }

    /**
     * Getter for Channel.
     * @return Returns the String
     */
    @JsonGetter("channel")
    public String getChannel() {
        return channel;
    }

    /**
     * Setter for Channel.
     * @param channel Value for String
     */
    @JsonSetter("channel")
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * Getter for Message.
     * @return Returns the MessageObject1
     */
    @JsonGetter("message")
    public MessageObject1 getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for MessageObject1
     */
    @JsonSetter("message")
    public void setMessage(MessageObject1 message) {
        this.message = message;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Text.
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for Ts.
     * @return Returns the String
     */
    @JsonGetter("ts")
    public String getTs() {
        return ts;
    }

    /**
     * Setter for Ts.
     * @param ts Value for String
     */
    @JsonSetter("ts")
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ChatUpdateSuccessSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChatUpdateSuccessSchema [" + "channel=" + channel + ", message=" + message + ", ok="
                + ok + ", text=" + text + ", ts=" + ts + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ChatUpdateSuccessSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChatUpdateSuccessSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(channel, message, ok, text, ts);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ChatUpdateSuccessSchema}.
     */
    public static class Builder {
        private String channel;
        private MessageObject1 message;
        private String ok = "True";
        private String text;
        private String ts;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  channel  String value for channel.
         * @param  message  MessageObject1 value for message.
         * @param  ok  String value for ok.
         * @param  text  String value for text.
         * @param  ts  String value for ts.
         */
        public Builder(String channel, MessageObject1 message, String ok, String text, String ts) {
            this.channel = channel;
            this.message = message;
            this.ok = ok;
            this.text = text;
            this.ts = ts;
        }

        /**
         * Setter for channel.
         * @param  channel  String value for channel.
         * @return Builder
         */
        public Builder channel(String channel) {
            this.channel = channel;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  MessageObject1 value for message.
         * @return Builder
         */
        public Builder message(MessageObject1 message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Setter for ts.
         * @param  ts  String value for ts.
         * @return Builder
         */
        public Builder ts(String ts) {
            this.ts = ts;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ChatUpdateSuccessSchema} object using the set fields.
         * @return {@link ChatUpdateSuccessSchema}
         */
        public ChatUpdateSuccessSchema build() {
            ChatUpdateSuccessSchema model =
                    new ChatUpdateSuccessSchema(channel, message, ok, text, ts);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
