/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DndSetSnoozeSchema type.
 */
public class DndSetSnoozeSchema {
    private String ok;
    private boolean snoozeEnabled;
    private int snoozeEndtime;
    private int snoozeRemaining;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DndSetSnoozeSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  ok  String value for ok.
     * @param  snoozeEnabled  boolean value for snoozeEnabled.
     * @param  snoozeEndtime  int value for snoozeEndtime.
     * @param  snoozeRemaining  int value for snoozeRemaining.
     */
    public DndSetSnoozeSchema(
            String ok,
            boolean snoozeEnabled,
            int snoozeEndtime,
            int snoozeRemaining) {
        this.ok = ok;
        this.snoozeEnabled = snoozeEnabled;
        this.snoozeEndtime = snoozeEndtime;
        this.snoozeRemaining = snoozeRemaining;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for SnoozeEnabled.
     * @return Returns the boolean
     */
    @JsonGetter("snooze_enabled")
    public boolean getSnoozeEnabled() {
        return snoozeEnabled;
    }

    /**
     * Setter for SnoozeEnabled.
     * @param snoozeEnabled Value for boolean
     */
    @JsonSetter("snooze_enabled")
    public void setSnoozeEnabled(boolean snoozeEnabled) {
        this.snoozeEnabled = snoozeEnabled;
    }

    /**
     * Getter for SnoozeEndtime.
     * @return Returns the int
     */
    @JsonGetter("snooze_endtime")
    public int getSnoozeEndtime() {
        return snoozeEndtime;
    }

    /**
     * Setter for SnoozeEndtime.
     * @param snoozeEndtime Value for int
     */
    @JsonSetter("snooze_endtime")
    public void setSnoozeEndtime(int snoozeEndtime) {
        this.snoozeEndtime = snoozeEndtime;
    }

    /**
     * Getter for SnoozeRemaining.
     * @return Returns the int
     */
    @JsonGetter("snooze_remaining")
    public int getSnoozeRemaining() {
        return snoozeRemaining;
    }

    /**
     * Setter for SnoozeRemaining.
     * @param snoozeRemaining Value for int
     */
    @JsonSetter("snooze_remaining")
    public void setSnoozeRemaining(int snoozeRemaining) {
        this.snoozeRemaining = snoozeRemaining;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DndSetSnoozeSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DndSetSnoozeSchema [" + "ok=" + ok + ", snoozeEnabled=" + snoozeEnabled
                + ", snoozeEndtime=" + snoozeEndtime + ", snoozeRemaining=" + snoozeRemaining
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DndSetSnoozeSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DndSetSnoozeSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ok, snoozeEnabled, snoozeEndtime, snoozeRemaining);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DndSetSnoozeSchema}.
     */
    public static class Builder {
        private String ok = "True";
        private boolean snoozeEnabled;
        private int snoozeEndtime;
        private int snoozeRemaining;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ok  String value for ok.
         * @param  snoozeEnabled  boolean value for snoozeEnabled.
         * @param  snoozeEndtime  int value for snoozeEndtime.
         * @param  snoozeRemaining  int value for snoozeRemaining.
         */
        public Builder(String ok, boolean snoozeEnabled, int snoozeEndtime, int snoozeRemaining) {
            this.ok = ok;
            this.snoozeEnabled = snoozeEnabled;
            this.snoozeEndtime = snoozeEndtime;
            this.snoozeRemaining = snoozeRemaining;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for snoozeEnabled.
         * @param  snoozeEnabled  boolean value for snoozeEnabled.
         * @return Builder
         */
        public Builder snoozeEnabled(boolean snoozeEnabled) {
            this.snoozeEnabled = snoozeEnabled;
            return this;
        }

        /**
         * Setter for snoozeEndtime.
         * @param  snoozeEndtime  int value for snoozeEndtime.
         * @return Builder
         */
        public Builder snoozeEndtime(int snoozeEndtime) {
            this.snoozeEndtime = snoozeEndtime;
            return this;
        }

        /**
         * Setter for snoozeRemaining.
         * @param  snoozeRemaining  int value for snoozeRemaining.
         * @return Builder
         */
        public Builder snoozeRemaining(int snoozeRemaining) {
            this.snoozeRemaining = snoozeRemaining;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DndSetSnoozeSchema} object using the set fields.
         * @return {@link DndSetSnoozeSchema}
         */
        public DndSetSnoozeSchema build() {
            DndSetSnoozeSchema model =
                    new DndSetSnoozeSchema(ok, snoozeEnabled, snoozeEndtime, snoozeRemaining);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
