/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error75 to be used.
 */
public enum Error75 {
    BAD_TIMESTAMP,

    MESSAGE_NOT_FOUND,

    FILE_NOT_FOUND,

    FILE_COMMENT_NOT_FOUND,

    CHANNEL_NOT_FOUND,

    NO_ITEM_SPECIFIED,

    ALREADY_STARRED,

    NOT_AUTHED,

    INVALID_AUTH,

    ACCOUNT_INACTIVE,

    TOKEN_REVOKED,

    NO_PERMISSION,

    ORG_LOGIN_REQUIRED,

    INVALID_ARG_NAME,

    INVALID_ARRAY_ARG,

    INVALID_CHARSET,

    INVALID_FORM_DATA,

    INVALID_POST_TYPE,

    MISSING_POST_TYPE,

    TEAM_ADDED_TO_ORG,

    INVALID_JSON,

    JSON_NOT_OBJECT,

    REQUEST_TIMEOUT,

    UPGRADE_REQUIRED,

    FATAL_ERROR;


    private static TreeMap<String, Error75> valueMap = new TreeMap<>();
    private String value;

    static {
        BAD_TIMESTAMP.value = "bad_timestamp";
        MESSAGE_NOT_FOUND.value = "message_not_found";
        FILE_NOT_FOUND.value = "file_not_found";
        FILE_COMMENT_NOT_FOUND.value = "file_comment_not_found";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        NO_ITEM_SPECIFIED.value = "no_item_specified";
        ALREADY_STARRED.value = "already_starred";
        NOT_AUTHED.value = "not_authed";
        INVALID_AUTH.value = "invalid_auth";
        ACCOUNT_INACTIVE.value = "account_inactive";
        TOKEN_REVOKED.value = "token_revoked";
        NO_PERMISSION.value = "no_permission";
        ORG_LOGIN_REQUIRED.value = "org_login_required";
        INVALID_ARG_NAME.value = "invalid_arg_name";
        INVALID_ARRAY_ARG.value = "invalid_array_arg";
        INVALID_CHARSET.value = "invalid_charset";
        INVALID_FORM_DATA.value = "invalid_form_data";
        INVALID_POST_TYPE.value = "invalid_post_type";
        MISSING_POST_TYPE.value = "missing_post_type";
        TEAM_ADDED_TO_ORG.value = "team_added_to_org";
        INVALID_JSON.value = "invalid_json";
        JSON_NOT_OBJECT.value = "json_not_object";
        REQUEST_TIMEOUT.value = "request_timeout";
        UPGRADE_REQUIRED.value = "upgrade_required";
        FATAL_ERROR.value = "fatal_error";

        valueMap.put("bad_timestamp", BAD_TIMESTAMP);
        valueMap.put("message_not_found", MESSAGE_NOT_FOUND);
        valueMap.put("file_not_found", FILE_NOT_FOUND);
        valueMap.put("file_comment_not_found", FILE_COMMENT_NOT_FOUND);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("no_item_specified", NO_ITEM_SPECIFIED);
        valueMap.put("already_starred", ALREADY_STARRED);
        valueMap.put("not_authed", NOT_AUTHED);
        valueMap.put("invalid_auth", INVALID_AUTH);
        valueMap.put("account_inactive", ACCOUNT_INACTIVE);
        valueMap.put("token_revoked", TOKEN_REVOKED);
        valueMap.put("no_permission", NO_PERMISSION);
        valueMap.put("org_login_required", ORG_LOGIN_REQUIRED);
        valueMap.put("invalid_arg_name", INVALID_ARG_NAME);
        valueMap.put("invalid_array_arg", INVALID_ARRAY_ARG);
        valueMap.put("invalid_charset", INVALID_CHARSET);
        valueMap.put("invalid_form_data", INVALID_FORM_DATA);
        valueMap.put("invalid_post_type", INVALID_POST_TYPE);
        valueMap.put("missing_post_type", MISSING_POST_TYPE);
        valueMap.put("team_added_to_org", TEAM_ADDED_TO_ORG);
        valueMap.put("invalid_json", INVALID_JSON);
        valueMap.put("json_not_object", JSON_NOT_OBJECT);
        valueMap.put("request_timeout", REQUEST_TIMEOUT);
        valueMap.put("upgrade_required", UPGRADE_REQUIRED);
        valueMap.put("fatal_error", FATAL_ERROR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error75 constructFromString(String toConvert) throws IOException {
        Error75 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error75 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error75 values to list of string values.
     * @param toConvert The list of Error75 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error75> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error75 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 