/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error7 to be used.
 */
public enum Error7 {
    FEATURE_NOT_ENABLED,

    CHANNEL_NOT_FOUND,

    CHANNEL_TYPE_NOT_SUPPORTED,

    DEFAULT_ORG_WIDE_CHANNEL,

    RESTRICTED_ACTION,

    USER_MUST_BE_ADMIN,

    FAILED_FOR_SOME_USERS;


    private static TreeMap<String, Error7> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        CHANNEL_TYPE_NOT_SUPPORTED.value = "channel_type_not_supported";
        DEFAULT_ORG_WIDE_CHANNEL.value = "default_org_wide_channel";
        RESTRICTED_ACTION.value = "restricted_action";
        USER_MUST_BE_ADMIN.value = "user_must_be_admin";
        FAILED_FOR_SOME_USERS.value = "failed_for_some_users";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("channel_type_not_supported", CHANNEL_TYPE_NOT_SUPPORTED);
        valueMap.put("default_org_wide_channel", DEFAULT_ORG_WIDE_CHANNEL);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("user_must_be_admin", USER_MUST_BE_ADMIN);
        valueMap.put("failed_for_some_users", FAILED_FOR_SOME_USERS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error7 constructFromString(String toConvert) throws IOException {
        Error7 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error7 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error7 values to list of string values.
     * @param toConvert The list of Error7 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error7> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error7 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 