/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error9 to be used.
 */
public enum Error9 {
    FEATURE_NOT_ENABLED,

    NOT_AN_ADMIN,

    NOT_AN_ENTERPRISE,

    TEAM_NOT_FOUND,

    NOT_ALLOWED,

    INVALID_AUTH,

    INVALID_CURSOR,

    INVALID_SEARCH_CHANNEL_TYPE,

    INVALID_SORT,

    INVALID_SORT_DIR;


    private static TreeMap<String, Error9> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        NOT_AN_ADMIN.value = "not_an_admin";
        NOT_AN_ENTERPRISE.value = "not_an_enterprise";
        TEAM_NOT_FOUND.value = "team_not_found";
        NOT_ALLOWED.value = "not_allowed";
        INVALID_AUTH.value = "invalid_auth";
        INVALID_CURSOR.value = "invalid_cursor";
        INVALID_SEARCH_CHANNEL_TYPE.value = "invalid_search_channel_type";
        INVALID_SORT.value = "invalid_sort";
        INVALID_SORT_DIR.value = "invalid_sort_dir";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("not_an_admin", NOT_AN_ADMIN);
        valueMap.put("not_an_enterprise", NOT_AN_ENTERPRISE);
        valueMap.put("team_not_found", TEAM_NOT_FOUND);
        valueMap.put("not_allowed", NOT_ALLOWED);
        valueMap.put("invalid_auth", INVALID_AUTH);
        valueMap.put("invalid_cursor", INVALID_CURSOR);
        valueMap.put("invalid_search_channel_type", INVALID_SEARCH_CHANNEL_TYPE);
        valueMap.put("invalid_sort", INVALID_SORT);
        valueMap.put("invalid_sort_dir", INVALID_SORT_DIR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error9 constructFromString(String toConvert) throws IOException {
        Error9 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error9 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error9 values to list of string values.
     * @param toConvert The list of Error9 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error9> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error9 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 