/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error to be used.
 */
public enum Error {
    FEATURE_NOT_ENABLED,

    CHANNEL_NOT_FOUND,

    CHANNEL_TYPE_NOT_SUPPORTED,

    DEFAULT_ORG_WIDE_CHANNEL,

    ALREADY_ARCHIVED,

    CANT_ARCHIVE_GENERAL,

    RESTRICTED_ACTION,

    COULD_NOT_ARCHIVE_CHANNEL;


    private static TreeMap<String, Error> valueMap = new TreeMap<>();
    private String value;

    static {
        FEATURE_NOT_ENABLED.value = "feature_not_enabled";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        CHANNEL_TYPE_NOT_SUPPORTED.value = "channel_type_not_supported";
        DEFAULT_ORG_WIDE_CHANNEL.value = "default_org_wide_channel";
        ALREADY_ARCHIVED.value = "already_archived";
        CANT_ARCHIVE_GENERAL.value = "cant_archive_general";
        RESTRICTED_ACTION.value = "restricted_action";
        COULD_NOT_ARCHIVE_CHANNEL.value = "could_not_archive_channel";

        valueMap.put("feature_not_enabled", FEATURE_NOT_ENABLED);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("channel_type_not_supported", CHANNEL_TYPE_NOT_SUPPORTED);
        valueMap.put("default_org_wide_channel", DEFAULT_ORG_WIDE_CHANNEL);
        valueMap.put("already_archived", ALREADY_ARCHIVED);
        valueMap.put("cant_archive_general", CANT_ARCHIVE_GENERAL);
        valueMap.put("restricted_action", RESTRICTED_ACTION);
        valueMap.put("could_not_archive_channel", COULD_NOT_ARCHIVE_CHANNEL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error constructFromString(String toConvert) throws IOException {
        Error enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error values to list of string values.
     * @param toConvert The list of Error values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 