/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Error29 to be used.
 */
public enum Error29 {
    MESSAGE_NOT_FOUND,

    CANT_UPDATE_MESSAGE,

    CHANNEL_NOT_FOUND,

    EDIT_WINDOW_CLOSED,

    MSG_TOO_LONG,

    TOO_MANY_ATTACHMENTS,

    RATE_LIMITED,

    NO_TEXT,

    NOT_AUTHED,

    INVALID_AUTH,

    ACCOUNT_INACTIVE,

    TOKEN_REVOKED,

    NO_PERMISSION,

    INVALID_ARG_NAME,

    INVALID_ARRAY_ARG,

    INVALID_CHARSET,

    INVALID_FORM_DATA,

    INVALID_POST_TYPE,

    MISSING_POST_TYPE,

    REQUEST_TIMEOUT,

    INVALID_JSON,

    JSON_NOT_OBJECT,

    UPGRADE_REQUIRED,

    FATAL_ERROR,

    IS_INACTIVE;


    private static TreeMap<String, Error29> valueMap = new TreeMap<>();
    private String value;

    static {
        MESSAGE_NOT_FOUND.value = "message_not_found";
        CANT_UPDATE_MESSAGE.value = "cant_update_message";
        CHANNEL_NOT_FOUND.value = "channel_not_found";
        EDIT_WINDOW_CLOSED.value = "edit_window_closed";
        MSG_TOO_LONG.value = "msg_too_long";
        TOO_MANY_ATTACHMENTS.value = "too_many_attachments";
        RATE_LIMITED.value = "rate_limited";
        NO_TEXT.value = "no_text";
        NOT_AUTHED.value = "not_authed";
        INVALID_AUTH.value = "invalid_auth";
        ACCOUNT_INACTIVE.value = "account_inactive";
        TOKEN_REVOKED.value = "token_revoked";
        NO_PERMISSION.value = "no_permission";
        INVALID_ARG_NAME.value = "invalid_arg_name";
        INVALID_ARRAY_ARG.value = "invalid_array_arg";
        INVALID_CHARSET.value = "invalid_charset";
        INVALID_FORM_DATA.value = "invalid_form_data";
        INVALID_POST_TYPE.value = "invalid_post_type";
        MISSING_POST_TYPE.value = "missing_post_type";
        REQUEST_TIMEOUT.value = "request_timeout";
        INVALID_JSON.value = "invalid_json";
        JSON_NOT_OBJECT.value = "json_not_object";
        UPGRADE_REQUIRED.value = "upgrade_required";
        FATAL_ERROR.value = "fatal_error";
        IS_INACTIVE.value = "is_inactive";

        valueMap.put("message_not_found", MESSAGE_NOT_FOUND);
        valueMap.put("cant_update_message", CANT_UPDATE_MESSAGE);
        valueMap.put("channel_not_found", CHANNEL_NOT_FOUND);
        valueMap.put("edit_window_closed", EDIT_WINDOW_CLOSED);
        valueMap.put("msg_too_long", MSG_TOO_LONG);
        valueMap.put("too_many_attachments", TOO_MANY_ATTACHMENTS);
        valueMap.put("rate_limited", RATE_LIMITED);
        valueMap.put("no_text", NO_TEXT);
        valueMap.put("not_authed", NOT_AUTHED);
        valueMap.put("invalid_auth", INVALID_AUTH);
        valueMap.put("account_inactive", ACCOUNT_INACTIVE);
        valueMap.put("token_revoked", TOKEN_REVOKED);
        valueMap.put("no_permission", NO_PERMISSION);
        valueMap.put("invalid_arg_name", INVALID_ARG_NAME);
        valueMap.put("invalid_array_arg", INVALID_ARRAY_ARG);
        valueMap.put("invalid_charset", INVALID_CHARSET);
        valueMap.put("invalid_form_data", INVALID_FORM_DATA);
        valueMap.put("invalid_post_type", INVALID_POST_TYPE);
        valueMap.put("missing_post_type", MISSING_POST_TYPE);
        valueMap.put("request_timeout", REQUEST_TIMEOUT);
        valueMap.put("invalid_json", INVALID_JSON);
        valueMap.put("json_not_object", JSON_NOT_OBJECT);
        valueMap.put("upgrade_required", UPGRADE_REQUIRED);
        valueMap.put("fatal_error", FATAL_ERROR);
        valueMap.put("is_inactive", IS_INACTIVE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Error29 constructFromString(String toConvert) throws IOException {
        Error29 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Error29 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Error29 values to list of string values.
     * @param toConvert The list of Error29 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Error29> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Error29 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 