/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for FileCommentObject type.
 */
public class FileCommentObject {
    private String comment;
    private int created;
    private String id;
    private boolean isIntro;
    private Boolean isStarred;
    private Integer numStars;
    private Object pinnedInfo;
    private List<String> pinnedTo;
    private List<ReactionObject> reactions;
    private int timestamp;
    private String user;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FileCommentObject() {
    }

    /**
     * Initialization constructor.
     * @param  comment  String value for comment.
     * @param  created  int value for created.
     * @param  id  String value for id.
     * @param  isIntro  boolean value for isIntro.
     * @param  timestamp  int value for timestamp.
     * @param  user  String value for user.
     * @param  isStarred  Boolean value for isStarred.
     * @param  numStars  Integer value for numStars.
     * @param  pinnedInfo  Object value for pinnedInfo.
     * @param  pinnedTo  List of String value for pinnedTo.
     * @param  reactions  List of ReactionObject value for reactions.
     */
    public FileCommentObject(
            String comment,
            int created,
            String id,
            boolean isIntro,
            int timestamp,
            String user,
            Boolean isStarred,
            Integer numStars,
            Object pinnedInfo,
            List<String> pinnedTo,
            List<ReactionObject> reactions) {
        this.comment = comment;
        this.created = created;
        this.id = id;
        this.isIntro = isIntro;
        this.isStarred = isStarred;
        this.numStars = numStars;
        this.pinnedInfo = pinnedInfo;
        this.pinnedTo = pinnedTo;
        this.reactions = reactions;
        this.timestamp = timestamp;
        this.user = user;
    }

    /**
     * Getter for Comment.
     * @return Returns the String
     */
    @JsonGetter("comment")
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for Created.
     * @return Returns the int
     */
    @JsonGetter("created")
    public int getCreated() {
        return created;
    }

    /**
     * Setter for Created.
     * @param created Value for int
     */
    @JsonSetter("created")
    public void setCreated(int created) {
        this.created = created;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for IsIntro.
     * @return Returns the boolean
     */
    @JsonGetter("is_intro")
    public boolean getIsIntro() {
        return isIntro;
    }

    /**
     * Setter for IsIntro.
     * @param isIntro Value for boolean
     */
    @JsonSetter("is_intro")
    public void setIsIntro(boolean isIntro) {
        this.isIntro = isIntro;
    }

    /**
     * Getter for IsStarred.
     * @return Returns the Boolean
     */
    @JsonGetter("is_starred")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsStarred() {
        return isStarred;
    }

    /**
     * Setter for IsStarred.
     * @param isStarred Value for Boolean
     */
    @JsonSetter("is_starred")
    public void setIsStarred(Boolean isStarred) {
        this.isStarred = isStarred;
    }

    /**
     * Getter for NumStars.
     * @return Returns the Integer
     */
    @JsonGetter("num_stars")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumStars() {
        return numStars;
    }

    /**
     * Setter for NumStars.
     * @param numStars Value for Integer
     */
    @JsonSetter("num_stars")
    public void setNumStars(Integer numStars) {
        this.numStars = numStars;
    }

    /**
     * Getter for PinnedInfo.
     * @return Returns the Object
     */
    @JsonGetter("pinned_info")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getPinnedInfo() {
        return pinnedInfo;
    }

    /**
     * Setter for PinnedInfo.
     * @param pinnedInfo Value for Object
     */
    @JsonSetter("pinned_info")
    public void setPinnedInfo(Object pinnedInfo) {
        this.pinnedInfo = pinnedInfo;
    }

    /**
     * Getter for PinnedTo.
     * @return Returns the List of String
     */
    @JsonGetter("pinned_to")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPinnedTo() {
        return pinnedTo;
    }

    /**
     * Setter for PinnedTo.
     * @param pinnedTo Value for List of String
     */
    @JsonSetter("pinned_to")
    public void setPinnedTo(List<String> pinnedTo) {
        this.pinnedTo = pinnedTo;
    }

    /**
     * Getter for Reactions.
     * @return Returns the List of ReactionObject
     */
    @JsonGetter("reactions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ReactionObject> getReactions() {
        return reactions;
    }

    /**
     * Setter for Reactions.
     * @param reactions Value for List of ReactionObject
     */
    @JsonSetter("reactions")
    public void setReactions(List<ReactionObject> reactions) {
        this.reactions = reactions;
    }

    /**
     * Getter for Timestamp.
     * @return Returns the int
     */
    @JsonGetter("timestamp")
    public int getTimestamp() {
        return timestamp;
    }

    /**
     * Setter for Timestamp.
     * @param timestamp Value for int
     */
    @JsonSetter("timestamp")
    public void setTimestamp(int timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for User.
     * @return Returns the String
     */
    @JsonGetter("user")
    public String getUser() {
        return user;
    }

    /**
     * Setter for User.
     * @param user Value for String
     */
    @JsonSetter("user")
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FileCommentObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FileCommentObject [" + "comment=" + comment + ", created=" + created + ", id=" + id
                + ", isIntro=" + isIntro + ", timestamp=" + timestamp + ", user=" + user
                + ", isStarred=" + isStarred + ", numStars=" + numStars + ", pinnedInfo="
                + pinnedInfo + ", pinnedTo=" + pinnedTo + ", reactions=" + reactions
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FileCommentObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FileCommentObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(comment, created, id, isIntro, timestamp, user)
                .isStarred(getIsStarred())
                .numStars(getNumStars())
                .pinnedInfo(getPinnedInfo())
                .pinnedTo(getPinnedTo())
                .reactions(getReactions());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FileCommentObject}.
     */
    public static class Builder {
        private String comment;
        private int created;
        private String id;
        private boolean isIntro;
        private int timestamp;
        private String user;
        private Boolean isStarred;
        private Integer numStars;
        private Object pinnedInfo;
        private List<String> pinnedTo;
        private List<ReactionObject> reactions;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  comment  String value for comment.
         * @param  created  int value for created.
         * @param  id  String value for id.
         * @param  isIntro  boolean value for isIntro.
         * @param  timestamp  int value for timestamp.
         * @param  user  String value for user.
         */
        public Builder(String comment, int created, String id, boolean isIntro, int timestamp,
                String user) {
            this.comment = comment;
            this.created = created;
            this.id = id;
            this.isIntro = isIntro;
            this.timestamp = timestamp;
            this.user = user;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for created.
         * @param  created  int value for created.
         * @return Builder
         */
        public Builder created(int created) {
            this.created = created;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for isIntro.
         * @param  isIntro  boolean value for isIntro.
         * @return Builder
         */
        public Builder isIntro(boolean isIntro) {
            this.isIntro = isIntro;
            return this;
        }

        /**
         * Setter for timestamp.
         * @param  timestamp  int value for timestamp.
         * @return Builder
         */
        public Builder timestamp(int timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * Setter for user.
         * @param  user  String value for user.
         * @return Builder
         */
        public Builder user(String user) {
            this.user = user;
            return this;
        }

        /**
         * Setter for isStarred.
         * @param  isStarred  Boolean value for isStarred.
         * @return Builder
         */
        public Builder isStarred(Boolean isStarred) {
            this.isStarred = isStarred;
            return this;
        }

        /**
         * Setter for numStars.
         * @param  numStars  Integer value for numStars.
         * @return Builder
         */
        public Builder numStars(Integer numStars) {
            this.numStars = numStars;
            return this;
        }

        /**
         * Setter for pinnedInfo.
         * @param  pinnedInfo  Object value for pinnedInfo.
         * @return Builder
         */
        public Builder pinnedInfo(Object pinnedInfo) {
            this.pinnedInfo = pinnedInfo;
            return this;
        }

        /**
         * Setter for pinnedTo.
         * @param  pinnedTo  List of String value for pinnedTo.
         * @return Builder
         */
        public Builder pinnedTo(List<String> pinnedTo) {
            this.pinnedTo = pinnedTo;
            return this;
        }

        /**
         * Setter for reactions.
         * @param  reactions  List of ReactionObject value for reactions.
         * @return Builder
         */
        public Builder reactions(List<ReactionObject> reactions) {
            this.reactions = reactions;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FileCommentObject} object using the set fields.
         * @return {@link FileCommentObject}
         */
        public FileCommentObject build() {
            FileCommentObject model =
                    new FileCommentObject(comment, created, id, isIntro, timestamp, user, isStarred,
                            numStars, pinnedInfo, pinnedTo, reactions);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
