/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for FilesUploadSchema type.
 */
public class FilesUploadSchema {
    private FileObject file;
    private String ok;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FilesUploadSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  file  FileObject value for file.
     * @param  ok  String value for ok.
     */
    public FilesUploadSchema(
            FileObject file,
            String ok) {
        this.file = file;
        this.ok = ok;
    }

    /**
     * Getter for File.
     * @return Returns the FileObject
     */
    @JsonGetter("file")
    public FileObject getFile() {
        return file;
    }

    /**
     * Setter for File.
     * @param file Value for FileObject
     */
    @JsonSetter("file")
    public void setFile(FileObject file) {
        this.file = file;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FilesUploadSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FilesUploadSchema [" + "file=" + file + ", ok=" + ok + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FilesUploadSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FilesUploadSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(file, ok);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FilesUploadSchema}.
     */
    public static class Builder {
        private FileObject file;
        private String ok = "True";
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  file  FileObject value for file.
         * @param  ok  String value for ok.
         */
        public Builder(FileObject file, String ok) {
            this.file = file;
            this.ok = ok;
        }

        /**
         * Setter for file.
         * @param  file  FileObject value for file.
         * @return Builder
         */
        public Builder file(FileObject file) {
            this.file = file;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FilesUploadSchema} object using the set fields.
         * @return {@link FilesUploadSchema}
         */
        public FilesUploadSchema build() {
            FilesUploadSchema model =
                    new FilesUploadSchema(file, ok);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
