/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Info type.
 */
public class Info {
    private AppHome appHome;
    private Channel channel;
    private Group group;
    private Im im;
    private Mpim mpim;
    private Team team;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Info() {
    }

    /**
     * Initialization constructor.
     * @param  appHome  AppHome value for appHome.
     * @param  channel  Channel value for channel.
     * @param  group  Group value for group.
     * @param  im  Im value for im.
     * @param  mpim  Mpim value for mpim.
     * @param  team  Team value for team.
     */
    public Info(
            AppHome appHome,
            Channel channel,
            Group group,
            Im im,
            Mpim mpim,
            Team team) {
        this.appHome = appHome;
        this.channel = channel;
        this.group = group;
        this.im = im;
        this.mpim = mpim;
        this.team = team;
    }

    /**
     * Getter for AppHome.
     * @return Returns the AppHome
     */
    @JsonGetter("app_home")
    public AppHome getAppHome() {
        return appHome;
    }

    /**
     * Setter for AppHome.
     * @param appHome Value for AppHome
     */
    @JsonSetter("app_home")
    public void setAppHome(AppHome appHome) {
        this.appHome = appHome;
    }

    /**
     * Getter for Channel.
     * @return Returns the Channel
     */
    @JsonGetter("channel")
    public Channel getChannel() {
        return channel;
    }

    /**
     * Setter for Channel.
     * @param channel Value for Channel
     */
    @JsonSetter("channel")
    public void setChannel(Channel channel) {
        this.channel = channel;
    }

    /**
     * Getter for Group.
     * @return Returns the Group
     */
    @JsonGetter("group")
    public Group getGroup() {
        return group;
    }

    /**
     * Setter for Group.
     * @param group Value for Group
     */
    @JsonSetter("group")
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     * Getter for Im.
     * @return Returns the Im
     */
    @JsonGetter("im")
    public Im getIm() {
        return im;
    }

    /**
     * Setter for Im.
     * @param im Value for Im
     */
    @JsonSetter("im")
    public void setIm(Im im) {
        this.im = im;
    }

    /**
     * Getter for Mpim.
     * @return Returns the Mpim
     */
    @JsonGetter("mpim")
    public Mpim getMpim() {
        return mpim;
    }

    /**
     * Setter for Mpim.
     * @param mpim Value for Mpim
     */
    @JsonSetter("mpim")
    public void setMpim(Mpim mpim) {
        this.mpim = mpim;
    }

    /**
     * Getter for Team.
     * @return Returns the Team
     */
    @JsonGetter("team")
    public Team getTeam() {
        return team;
    }

    /**
     * Setter for Team.
     * @param team Value for Team
     */
    @JsonSetter("team")
    public void setTeam(Team team) {
        this.team = team;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Info into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Info [" + "appHome=" + appHome + ", channel=" + channel + ", group=" + group
                + ", im=" + im + ", mpim=" + mpim + ", team=" + team + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Info.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Info.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(appHome, channel, group, im, mpim, team);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Info}.
     */
    public static class Builder {
        private AppHome appHome;
        private Channel channel;
        private Group group;
        private Im im;
        private Mpim mpim;
        private Team team;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  appHome  AppHome value for appHome.
         * @param  channel  Channel value for channel.
         * @param  group  Group value for group.
         * @param  im  Im value for im.
         * @param  mpim  Mpim value for mpim.
         * @param  team  Team value for team.
         */
        public Builder(AppHome appHome, Channel channel, Group group, Im im, Mpim mpim, Team team) {
            this.appHome = appHome;
            this.channel = channel;
            this.group = group;
            this.im = im;
            this.mpim = mpim;
            this.team = team;
        }

        /**
         * Setter for appHome.
         * @param  appHome  AppHome value for appHome.
         * @return Builder
         */
        public Builder appHome(AppHome appHome) {
            this.appHome = appHome;
            return this;
        }

        /**
         * Setter for channel.
         * @param  channel  Channel value for channel.
         * @return Builder
         */
        public Builder channel(Channel channel) {
            this.channel = channel;
            return this;
        }

        /**
         * Setter for group.
         * @param  group  Group value for group.
         * @return Builder
         */
        public Builder group(Group group) {
            this.group = group;
            return this;
        }

        /**
         * Setter for im.
         * @param  im  Im value for im.
         * @return Builder
         */
        public Builder im(Im im) {
            this.im = im;
            return this;
        }

        /**
         * Setter for mpim.
         * @param  mpim  Mpim value for mpim.
         * @return Builder
         */
        public Builder mpim(Mpim mpim) {
            this.mpim = mpim;
            return this;
        }

        /**
         * Setter for team.
         * @param  team  Team value for team.
         * @return Builder
         */
        public Builder team(Team team) {
            this.team = team;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Info} object using the set fields.
         * @return {@link Info}
         */
        public Info build() {
            Info model =
                    new Info(appHome, channel, group, im, mpim, team);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
