/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for MessageObject type.
 */
public class MessageObject {
    private List<Attachment> attachments;
    private List<BlockKitBlock> blocks;
    private Object botId;
    private BotProfileObject botProfile;
    private String clientMsgId;
    private FileCommentObject comment;
    private Boolean displayAsBot;
    private FileObject file;
    private List<FileObject> files;
    private Icons1 icons;
    private String inviter;
    private Boolean isDelayedMessage;
    private Boolean isIntro;
    private Boolean isStarred;
    private String lastRead;
    private String latestReply;
    private String name;
    private String oldName;
    private String parentUserId;
    private String permalink;
    private List<String> pinnedTo;
    private String purpose;
    private List<ReactionObject> reactions;
    private Integer replyCount;
    private List<String> replyUsers;
    private Integer replyUsersCount;
    private String sourceTeam;
    private Boolean subscribed;
    private String subtype;
    private String team;
    private String text;
    private String threadTs;
    private String topic;
    private String ts;
    private String type;
    private Integer unreadCount;
    private Boolean upload;
    private String user;
    private ObjsUserProfileShort userProfile;
    private String userTeam;
    private String username;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public MessageObject() {
    }

    /**
     * Initialization constructor.
     * @param  text  String value for text.
     * @param  ts  String value for ts.
     * @param  type  String value for type.
     * @param  attachments  List of Attachment value for attachments.
     * @param  blocks  List of BlockKitBlock value for blocks.
     * @param  botId  Object value for botId.
     * @param  botProfile  BotProfileObject value for botProfile.
     * @param  clientMsgId  String value for clientMsgId.
     * @param  comment  FileCommentObject value for comment.
     * @param  displayAsBot  Boolean value for displayAsBot.
     * @param  file  FileObject value for file.
     * @param  files  List of FileObject value for files.
     * @param  icons  Icons1 value for icons.
     * @param  inviter  String value for inviter.
     * @param  isDelayedMessage  Boolean value for isDelayedMessage.
     * @param  isIntro  Boolean value for isIntro.
     * @param  isStarred  Boolean value for isStarred.
     * @param  lastRead  String value for lastRead.
     * @param  latestReply  String value for latestReply.
     * @param  name  String value for name.
     * @param  oldName  String value for oldName.
     * @param  parentUserId  String value for parentUserId.
     * @param  permalink  String value for permalink.
     * @param  pinnedTo  List of String value for pinnedTo.
     * @param  purpose  String value for purpose.
     * @param  reactions  List of ReactionObject value for reactions.
     * @param  replyCount  Integer value for replyCount.
     * @param  replyUsers  List of String value for replyUsers.
     * @param  replyUsersCount  Integer value for replyUsersCount.
     * @param  sourceTeam  String value for sourceTeam.
     * @param  subscribed  Boolean value for subscribed.
     * @param  subtype  String value for subtype.
     * @param  team  String value for team.
     * @param  threadTs  String value for threadTs.
     * @param  topic  String value for topic.
     * @param  unreadCount  Integer value for unreadCount.
     * @param  upload  Boolean value for upload.
     * @param  user  String value for user.
     * @param  userProfile  ObjsUserProfileShort value for userProfile.
     * @param  userTeam  String value for userTeam.
     * @param  username  String value for username.
     */
    public MessageObject(
            String text,
            String ts,
            String type,
            List<Attachment> attachments,
            List<BlockKitBlock> blocks,
            Object botId,
            BotProfileObject botProfile,
            String clientMsgId,
            FileCommentObject comment,
            Boolean displayAsBot,
            FileObject file,
            List<FileObject> files,
            Icons1 icons,
            String inviter,
            Boolean isDelayedMessage,
            Boolean isIntro,
            Boolean isStarred,
            String lastRead,
            String latestReply,
            String name,
            String oldName,
            String parentUserId,
            String permalink,
            List<String> pinnedTo,
            String purpose,
            List<ReactionObject> reactions,
            Integer replyCount,
            List<String> replyUsers,
            Integer replyUsersCount,
            String sourceTeam,
            Boolean subscribed,
            String subtype,
            String team,
            String threadTs,
            String topic,
            Integer unreadCount,
            Boolean upload,
            String user,
            ObjsUserProfileShort userProfile,
            String userTeam,
            String username) {
        this.attachments = attachments;
        this.blocks = blocks;
        this.botId = botId;
        this.botProfile = botProfile;
        this.clientMsgId = clientMsgId;
        this.comment = comment;
        this.displayAsBot = displayAsBot;
        this.file = file;
        this.files = files;
        this.icons = icons;
        this.inviter = inviter;
        this.isDelayedMessage = isDelayedMessage;
        this.isIntro = isIntro;
        this.isStarred = isStarred;
        this.lastRead = lastRead;
        this.latestReply = latestReply;
        this.name = name;
        this.oldName = oldName;
        this.parentUserId = parentUserId;
        this.permalink = permalink;
        this.pinnedTo = pinnedTo;
        this.purpose = purpose;
        this.reactions = reactions;
        this.replyCount = replyCount;
        this.replyUsers = replyUsers;
        this.replyUsersCount = replyUsersCount;
        this.sourceTeam = sourceTeam;
        this.subscribed = subscribed;
        this.subtype = subtype;
        this.team = team;
        this.text = text;
        this.threadTs = threadTs;
        this.topic = topic;
        this.ts = ts;
        this.type = type;
        this.unreadCount = unreadCount;
        this.upload = upload;
        this.user = user;
        this.userProfile = userProfile;
        this.userTeam = userTeam;
        this.username = username;
    }

    /**
     * Getter for Attachments.
     * @return Returns the List of Attachment
     */
    @JsonGetter("attachments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Attachment> getAttachments() {
        return attachments;
    }

    /**
     * Setter for Attachments.
     * @param attachments Value for List of Attachment
     */
    @JsonSetter("attachments")
    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

    /**
     * Getter for Blocks.
     * This is a very loose definition, in the future, we'll populate this with deeper schema in
     * this definition namespace.
     * @return Returns the List of BlockKitBlock
     */
    @JsonGetter("blocks")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<BlockKitBlock> getBlocks() {
        return blocks;
    }

    /**
     * Setter for Blocks.
     * This is a very loose definition, in the future, we'll populate this with deeper schema in
     * this definition namespace.
     * @param blocks Value for List of BlockKitBlock
     */
    @JsonSetter("blocks")
    public void setBlocks(List<BlockKitBlock> blocks) {
        this.blocks = blocks;
    }

    /**
     * Getter for BotId.
     * @return Returns the Object
     */
    @JsonGetter("bot_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getBotId() {
        return botId;
    }

    /**
     * Setter for BotId.
     * @param botId Value for Object
     */
    @JsonSetter("bot_id")
    public void setBotId(Object botId) {
        this.botId = botId;
    }

    /**
     * Getter for BotProfile.
     * @return Returns the BotProfileObject
     */
    @JsonGetter("bot_profile")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BotProfileObject getBotProfile() {
        return botProfile;
    }

    /**
     * Setter for BotProfile.
     * @param botProfile Value for BotProfileObject
     */
    @JsonSetter("bot_profile")
    public void setBotProfile(BotProfileObject botProfile) {
        this.botProfile = botProfile;
    }

    /**
     * Getter for ClientMsgId.
     * @return Returns the String
     */
    @JsonGetter("client_msg_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getClientMsgId() {
        return clientMsgId;
    }

    /**
     * Setter for ClientMsgId.
     * @param clientMsgId Value for String
     */
    @JsonSetter("client_msg_id")
    public void setClientMsgId(String clientMsgId) {
        this.clientMsgId = clientMsgId;
    }

    /**
     * Getter for Comment.
     * @return Returns the FileCommentObject
     */
    @JsonGetter("comment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FileCommentObject getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * @param comment Value for FileCommentObject
     */
    @JsonSetter("comment")
    public void setComment(FileCommentObject comment) {
        this.comment = comment;
    }

    /**
     * Getter for DisplayAsBot.
     * @return Returns the Boolean
     */
    @JsonGetter("display_as_bot")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getDisplayAsBot() {
        return displayAsBot;
    }

    /**
     * Setter for DisplayAsBot.
     * @param displayAsBot Value for Boolean
     */
    @JsonSetter("display_as_bot")
    public void setDisplayAsBot(Boolean displayAsBot) {
        this.displayAsBot = displayAsBot;
    }

    /**
     * Getter for File.
     * @return Returns the FileObject
     */
    @JsonGetter("file")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FileObject getFile() {
        return file;
    }

    /**
     * Setter for File.
     * @param file Value for FileObject
     */
    @JsonSetter("file")
    public void setFile(FileObject file) {
        this.file = file;
    }

    /**
     * Getter for Files.
     * @return Returns the List of FileObject
     */
    @JsonGetter("files")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<FileObject> getFiles() {
        return files;
    }

    /**
     * Setter for Files.
     * @param files Value for List of FileObject
     */
    @JsonSetter("files")
    public void setFiles(List<FileObject> files) {
        this.files = files;
    }

    /**
     * Getter for Icons.
     * @return Returns the Icons1
     */
    @JsonGetter("icons")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Icons1 getIcons() {
        return icons;
    }

    /**
     * Setter for Icons.
     * @param icons Value for Icons1
     */
    @JsonSetter("icons")
    public void setIcons(Icons1 icons) {
        this.icons = icons;
    }

    /**
     * Getter for Inviter.
     * @return Returns the String
     */
    @JsonGetter("inviter")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInviter() {
        return inviter;
    }

    /**
     * Setter for Inviter.
     * @param inviter Value for String
     */
    @JsonSetter("inviter")
    public void setInviter(String inviter) {
        this.inviter = inviter;
    }

    /**
     * Getter for IsDelayedMessage.
     * @return Returns the Boolean
     */
    @JsonGetter("is_delayed_message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsDelayedMessage() {
        return isDelayedMessage;
    }

    /**
     * Setter for IsDelayedMessage.
     * @param isDelayedMessage Value for Boolean
     */
    @JsonSetter("is_delayed_message")
    public void setIsDelayedMessage(Boolean isDelayedMessage) {
        this.isDelayedMessage = isDelayedMessage;
    }

    /**
     * Getter for IsIntro.
     * @return Returns the Boolean
     */
    @JsonGetter("is_intro")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsIntro() {
        return isIntro;
    }

    /**
     * Setter for IsIntro.
     * @param isIntro Value for Boolean
     */
    @JsonSetter("is_intro")
    public void setIsIntro(Boolean isIntro) {
        this.isIntro = isIntro;
    }

    /**
     * Getter for IsStarred.
     * @return Returns the Boolean
     */
    @JsonGetter("is_starred")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsStarred() {
        return isStarred;
    }

    /**
     * Setter for IsStarred.
     * @param isStarred Value for Boolean
     */
    @JsonSetter("is_starred")
    public void setIsStarred(Boolean isStarred) {
        this.isStarred = isStarred;
    }

    /**
     * Getter for LastRead.
     * @return Returns the String
     */
    @JsonGetter("last_read")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastRead() {
        return lastRead;
    }

    /**
     * Setter for LastRead.
     * @param lastRead Value for String
     */
    @JsonSetter("last_read")
    public void setLastRead(String lastRead) {
        this.lastRead = lastRead;
    }

    /**
     * Getter for LatestReply.
     * @return Returns the String
     */
    @JsonGetter("latest_reply")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLatestReply() {
        return latestReply;
    }

    /**
     * Setter for LatestReply.
     * @param latestReply Value for String
     */
    @JsonSetter("latest_reply")
    public void setLatestReply(String latestReply) {
        this.latestReply = latestReply;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for OldName.
     * @return Returns the String
     */
    @JsonGetter("old_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOldName() {
        return oldName;
    }

    /**
     * Setter for OldName.
     * @param oldName Value for String
     */
    @JsonSetter("old_name")
    public void setOldName(String oldName) {
        this.oldName = oldName;
    }

    /**
     * Getter for ParentUserId.
     * @return Returns the String
     */
    @JsonGetter("parent_user_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getParentUserId() {
        return parentUserId;
    }

    /**
     * Setter for ParentUserId.
     * @param parentUserId Value for String
     */
    @JsonSetter("parent_user_id")
    public void setParentUserId(String parentUserId) {
        this.parentUserId = parentUserId;
    }

    /**
     * Getter for Permalink.
     * @return Returns the String
     */
    @JsonGetter("permalink")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPermalink() {
        return permalink;
    }

    /**
     * Setter for Permalink.
     * @param permalink Value for String
     */
    @JsonSetter("permalink")
    public void setPermalink(String permalink) {
        this.permalink = permalink;
    }

    /**
     * Getter for PinnedTo.
     * @return Returns the List of String
     */
    @JsonGetter("pinned_to")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPinnedTo() {
        return pinnedTo;
    }

    /**
     * Setter for PinnedTo.
     * @param pinnedTo Value for List of String
     */
    @JsonSetter("pinned_to")
    public void setPinnedTo(List<String> pinnedTo) {
        this.pinnedTo = pinnedTo;
    }

    /**
     * Getter for Purpose.
     * @return Returns the String
     */
    @JsonGetter("purpose")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPurpose() {
        return purpose;
    }

    /**
     * Setter for Purpose.
     * @param purpose Value for String
     */
    @JsonSetter("purpose")
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * Getter for Reactions.
     * @return Returns the List of ReactionObject
     */
    @JsonGetter("reactions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ReactionObject> getReactions() {
        return reactions;
    }

    /**
     * Setter for Reactions.
     * @param reactions Value for List of ReactionObject
     */
    @JsonSetter("reactions")
    public void setReactions(List<ReactionObject> reactions) {
        this.reactions = reactions;
    }

    /**
     * Getter for ReplyCount.
     * @return Returns the Integer
     */
    @JsonGetter("reply_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * Setter for ReplyCount.
     * @param replyCount Value for Integer
     */
    @JsonSetter("reply_count")
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * Getter for ReplyUsers.
     * @return Returns the List of String
     */
    @JsonGetter("reply_users")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getReplyUsers() {
        return replyUsers;
    }

    /**
     * Setter for ReplyUsers.
     * @param replyUsers Value for List of String
     */
    @JsonSetter("reply_users")
    public void setReplyUsers(List<String> replyUsers) {
        this.replyUsers = replyUsers;
    }

    /**
     * Getter for ReplyUsersCount.
     * @return Returns the Integer
     */
    @JsonGetter("reply_users_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReplyUsersCount() {
        return replyUsersCount;
    }

    /**
     * Setter for ReplyUsersCount.
     * @param replyUsersCount Value for Integer
     */
    @JsonSetter("reply_users_count")
    public void setReplyUsersCount(Integer replyUsersCount) {
        this.replyUsersCount = replyUsersCount;
    }

    /**
     * Getter for SourceTeam.
     * @return Returns the String
     */
    @JsonGetter("source_team")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSourceTeam() {
        return sourceTeam;
    }

    /**
     * Setter for SourceTeam.
     * @param sourceTeam Value for String
     */
    @JsonSetter("source_team")
    public void setSourceTeam(String sourceTeam) {
        this.sourceTeam = sourceTeam;
    }

    /**
     * Getter for Subscribed.
     * @return Returns the Boolean
     */
    @JsonGetter("subscribed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSubscribed() {
        return subscribed;
    }

    /**
     * Setter for Subscribed.
     * @param subscribed Value for Boolean
     */
    @JsonSetter("subscribed")
    public void setSubscribed(Boolean subscribed) {
        this.subscribed = subscribed;
    }

    /**
     * Getter for Subtype.
     * @return Returns the String
     */
    @JsonGetter("subtype")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSubtype() {
        return subtype;
    }

    /**
     * Setter for Subtype.
     * @param subtype Value for String
     */
    @JsonSetter("subtype")
    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    /**
     * Getter for Team.
     * @return Returns the String
     */
    @JsonGetter("team")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTeam() {
        return team;
    }

    /**
     * Setter for Team.
     * @param team Value for String
     */
    @JsonSetter("team")
    public void setTeam(String team) {
        this.team = team;
    }

    /**
     * Getter for Text.
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for ThreadTs.
     * @return Returns the String
     */
    @JsonGetter("thread_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getThreadTs() {
        return threadTs;
    }

    /**
     * Setter for ThreadTs.
     * @param threadTs Value for String
     */
    @JsonSetter("thread_ts")
    public void setThreadTs(String threadTs) {
        this.threadTs = threadTs;
    }

    /**
     * Getter for Topic.
     * @return Returns the String
     */
    @JsonGetter("topic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTopic() {
        return topic;
    }

    /**
     * Setter for Topic.
     * @param topic Value for String
     */
    @JsonSetter("topic")
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * Getter for Ts.
     * @return Returns the String
     */
    @JsonGetter("ts")
    public String getTs() {
        return ts;
    }

    /**
     * Setter for Ts.
     * @param ts Value for String
     */
    @JsonSetter("ts")
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for UnreadCount.
     * @return Returns the Integer
     */
    @JsonGetter("unread_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnreadCount() {
        return unreadCount;
    }

    /**
     * Setter for UnreadCount.
     * @param unreadCount Value for Integer
     */
    @JsonSetter("unread_count")
    public void setUnreadCount(Integer unreadCount) {
        this.unreadCount = unreadCount;
    }

    /**
     * Getter for Upload.
     * @return Returns the Boolean
     */
    @JsonGetter("upload")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getUpload() {
        return upload;
    }

    /**
     * Setter for Upload.
     * @param upload Value for Boolean
     */
    @JsonSetter("upload")
    public void setUpload(Boolean upload) {
        this.upload = upload;
    }

    /**
     * Getter for User.
     * @return Returns the String
     */
    @JsonGetter("user")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUser() {
        return user;
    }

    /**
     * Setter for User.
     * @param user Value for String
     */
    @JsonSetter("user")
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Getter for UserProfile.
     * @return Returns the ObjsUserProfileShort
     */
    @JsonGetter("user_profile")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ObjsUserProfileShort getUserProfile() {
        return userProfile;
    }

    /**
     * Setter for UserProfile.
     * @param userProfile Value for ObjsUserProfileShort
     */
    @JsonSetter("user_profile")
    public void setUserProfile(ObjsUserProfileShort userProfile) {
        this.userProfile = userProfile;
    }

    /**
     * Getter for UserTeam.
     * @return Returns the String
     */
    @JsonGetter("user_team")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUserTeam() {
        return userTeam;
    }

    /**
     * Setter for UserTeam.
     * @param userTeam Value for String
     */
    @JsonSetter("user_team")
    public void setUserTeam(String userTeam) {
        this.userTeam = userTeam;
    }

    /**
     * Getter for Username.
     * @return Returns the String
     */
    @JsonGetter("username")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this MessageObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MessageObject [" + "text=" + text + ", ts=" + ts + ", type=" + type
                + ", attachments=" + attachments + ", blocks=" + blocks + ", botId=" + botId
                + ", botProfile=" + botProfile + ", clientMsgId=" + clientMsgId + ", comment="
                + comment + ", displayAsBot=" + displayAsBot + ", file=" + file + ", files=" + files
                + ", icons=" + icons + ", inviter=" + inviter + ", isDelayedMessage="
                + isDelayedMessage + ", isIntro=" + isIntro + ", isStarred=" + isStarred
                + ", lastRead=" + lastRead + ", latestReply=" + latestReply + ", name=" + name
                + ", oldName=" + oldName + ", parentUserId=" + parentUserId + ", permalink="
                + permalink + ", pinnedTo=" + pinnedTo + ", purpose=" + purpose + ", reactions="
                + reactions + ", replyCount=" + replyCount + ", replyUsers=" + replyUsers
                + ", replyUsersCount=" + replyUsersCount + ", sourceTeam=" + sourceTeam
                + ", subscribed=" + subscribed + ", subtype=" + subtype + ", team=" + team
                + ", threadTs=" + threadTs + ", topic=" + topic + ", unreadCount=" + unreadCount
                + ", upload=" + upload + ", user=" + user + ", userProfile=" + userProfile
                + ", userTeam=" + userTeam + ", username=" + username + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link MessageObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MessageObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(text, ts, type)
                .attachments(getAttachments())
                .blocks(getBlocks())
                .botId(getBotId())
                .botProfile(getBotProfile())
                .clientMsgId(getClientMsgId())
                .comment(getComment())
                .displayAsBot(getDisplayAsBot())
                .file(getFile())
                .files(getFiles())
                .icons(getIcons())
                .inviter(getInviter())
                .isDelayedMessage(getIsDelayedMessage())
                .isIntro(getIsIntro())
                .isStarred(getIsStarred())
                .lastRead(getLastRead())
                .latestReply(getLatestReply())
                .name(getName())
                .oldName(getOldName())
                .parentUserId(getParentUserId())
                .permalink(getPermalink())
                .pinnedTo(getPinnedTo())
                .purpose(getPurpose())
                .reactions(getReactions())
                .replyCount(getReplyCount())
                .replyUsers(getReplyUsers())
                .replyUsersCount(getReplyUsersCount())
                .sourceTeam(getSourceTeam())
                .subscribed(getSubscribed())
                .subtype(getSubtype())
                .team(getTeam())
                .threadTs(getThreadTs())
                .topic(getTopic())
                .unreadCount(getUnreadCount())
                .upload(getUpload())
                .user(getUser())
                .userProfile(getUserProfile())
                .userTeam(getUserTeam())
                .username(getUsername());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link MessageObject}.
     */
    public static class Builder {
        private String text;
        private String ts;
        private String type;
        private List<Attachment> attachments;
        private List<BlockKitBlock> blocks;
        private Object botId;
        private BotProfileObject botProfile;
        private String clientMsgId;
        private FileCommentObject comment;
        private Boolean displayAsBot;
        private FileObject file;
        private List<FileObject> files;
        private Icons1 icons;
        private String inviter;
        private Boolean isDelayedMessage;
        private Boolean isIntro;
        private Boolean isStarred;
        private String lastRead;
        private String latestReply;
        private String name;
        private String oldName;
        private String parentUserId;
        private String permalink;
        private List<String> pinnedTo;
        private String purpose;
        private List<ReactionObject> reactions;
        private Integer replyCount;
        private List<String> replyUsers;
        private Integer replyUsersCount;
        private String sourceTeam;
        private Boolean subscribed;
        private String subtype;
        private String team;
        private String threadTs;
        private String topic;
        private Integer unreadCount;
        private Boolean upload;
        private String user;
        private ObjsUserProfileShort userProfile;
        private String userTeam;
        private String username;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  text  String value for text.
         * @param  ts  String value for ts.
         * @param  type  String value for type.
         */
        public Builder(String text, String ts, String type) {
            this.text = text;
            this.ts = ts;
            this.type = type;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Setter for ts.
         * @param  ts  String value for ts.
         * @return Builder
         */
        public Builder ts(String ts) {
            this.ts = ts;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for attachments.
         * @param  attachments  List of Attachment value for attachments.
         * @return Builder
         */
        public Builder attachments(List<Attachment> attachments) {
            this.attachments = attachments;
            return this;
        }

        /**
         * Setter for blocks.
         * @param  blocks  List of BlockKitBlock value for blocks.
         * @return Builder
         */
        public Builder blocks(List<BlockKitBlock> blocks) {
            this.blocks = blocks;
            return this;
        }

        /**
         * Setter for botId.
         * @param  botId  Object value for botId.
         * @return Builder
         */
        public Builder botId(Object botId) {
            this.botId = botId;
            return this;
        }

        /**
         * Setter for botProfile.
         * @param  botProfile  BotProfileObject value for botProfile.
         * @return Builder
         */
        public Builder botProfile(BotProfileObject botProfile) {
            this.botProfile = botProfile;
            return this;
        }

        /**
         * Setter for clientMsgId.
         * @param  clientMsgId  String value for clientMsgId.
         * @return Builder
         */
        public Builder clientMsgId(String clientMsgId) {
            this.clientMsgId = clientMsgId;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  FileCommentObject value for comment.
         * @return Builder
         */
        public Builder comment(FileCommentObject comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for displayAsBot.
         * @param  displayAsBot  Boolean value for displayAsBot.
         * @return Builder
         */
        public Builder displayAsBot(Boolean displayAsBot) {
            this.displayAsBot = displayAsBot;
            return this;
        }

        /**
         * Setter for file.
         * @param  file  FileObject value for file.
         * @return Builder
         */
        public Builder file(FileObject file) {
            this.file = file;
            return this;
        }

        /**
         * Setter for files.
         * @param  files  List of FileObject value for files.
         * @return Builder
         */
        public Builder files(List<FileObject> files) {
            this.files = files;
            return this;
        }

        /**
         * Setter for icons.
         * @param  icons  Icons1 value for icons.
         * @return Builder
         */
        public Builder icons(Icons1 icons) {
            this.icons = icons;
            return this;
        }

        /**
         * Setter for inviter.
         * @param  inviter  String value for inviter.
         * @return Builder
         */
        public Builder inviter(String inviter) {
            this.inviter = inviter;
            return this;
        }

        /**
         * Setter for isDelayedMessage.
         * @param  isDelayedMessage  Boolean value for isDelayedMessage.
         * @return Builder
         */
        public Builder isDelayedMessage(Boolean isDelayedMessage) {
            this.isDelayedMessage = isDelayedMessage;
            return this;
        }

        /**
         * Setter for isIntro.
         * @param  isIntro  Boolean value for isIntro.
         * @return Builder
         */
        public Builder isIntro(Boolean isIntro) {
            this.isIntro = isIntro;
            return this;
        }

        /**
         * Setter for isStarred.
         * @param  isStarred  Boolean value for isStarred.
         * @return Builder
         */
        public Builder isStarred(Boolean isStarred) {
            this.isStarred = isStarred;
            return this;
        }

        /**
         * Setter for lastRead.
         * @param  lastRead  String value for lastRead.
         * @return Builder
         */
        public Builder lastRead(String lastRead) {
            this.lastRead = lastRead;
            return this;
        }

        /**
         * Setter for latestReply.
         * @param  latestReply  String value for latestReply.
         * @return Builder
         */
        public Builder latestReply(String latestReply) {
            this.latestReply = latestReply;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for oldName.
         * @param  oldName  String value for oldName.
         * @return Builder
         */
        public Builder oldName(String oldName) {
            this.oldName = oldName;
            return this;
        }

        /**
         * Setter for parentUserId.
         * @param  parentUserId  String value for parentUserId.
         * @return Builder
         */
        public Builder parentUserId(String parentUserId) {
            this.parentUserId = parentUserId;
            return this;
        }

        /**
         * Setter for permalink.
         * @param  permalink  String value for permalink.
         * @return Builder
         */
        public Builder permalink(String permalink) {
            this.permalink = permalink;
            return this;
        }

        /**
         * Setter for pinnedTo.
         * @param  pinnedTo  List of String value for pinnedTo.
         * @return Builder
         */
        public Builder pinnedTo(List<String> pinnedTo) {
            this.pinnedTo = pinnedTo;
            return this;
        }

        /**
         * Setter for purpose.
         * @param  purpose  String value for purpose.
         * @return Builder
         */
        public Builder purpose(String purpose) {
            this.purpose = purpose;
            return this;
        }

        /**
         * Setter for reactions.
         * @param  reactions  List of ReactionObject value for reactions.
         * @return Builder
         */
        public Builder reactions(List<ReactionObject> reactions) {
            this.reactions = reactions;
            return this;
        }

        /**
         * Setter for replyCount.
         * @param  replyCount  Integer value for replyCount.
         * @return Builder
         */
        public Builder replyCount(Integer replyCount) {
            this.replyCount = replyCount;
            return this;
        }

        /**
         * Setter for replyUsers.
         * @param  replyUsers  List of String value for replyUsers.
         * @return Builder
         */
        public Builder replyUsers(List<String> replyUsers) {
            this.replyUsers = replyUsers;
            return this;
        }

        /**
         * Setter for replyUsersCount.
         * @param  replyUsersCount  Integer value for replyUsersCount.
         * @return Builder
         */
        public Builder replyUsersCount(Integer replyUsersCount) {
            this.replyUsersCount = replyUsersCount;
            return this;
        }

        /**
         * Setter for sourceTeam.
         * @param  sourceTeam  String value for sourceTeam.
         * @return Builder
         */
        public Builder sourceTeam(String sourceTeam) {
            this.sourceTeam = sourceTeam;
            return this;
        }

        /**
         * Setter for subscribed.
         * @param  subscribed  Boolean value for subscribed.
         * @return Builder
         */
        public Builder subscribed(Boolean subscribed) {
            this.subscribed = subscribed;
            return this;
        }

        /**
         * Setter for subtype.
         * @param  subtype  String value for subtype.
         * @return Builder
         */
        public Builder subtype(String subtype) {
            this.subtype = subtype;
            return this;
        }

        /**
         * Setter for team.
         * @param  team  String value for team.
         * @return Builder
         */
        public Builder team(String team) {
            this.team = team;
            return this;
        }

        /**
         * Setter for threadTs.
         * @param  threadTs  String value for threadTs.
         * @return Builder
         */
        public Builder threadTs(String threadTs) {
            this.threadTs = threadTs;
            return this;
        }

        /**
         * Setter for topic.
         * @param  topic  String value for topic.
         * @return Builder
         */
        public Builder topic(String topic) {
            this.topic = topic;
            return this;
        }

        /**
         * Setter for unreadCount.
         * @param  unreadCount  Integer value for unreadCount.
         * @return Builder
         */
        public Builder unreadCount(Integer unreadCount) {
            this.unreadCount = unreadCount;
            return this;
        }

        /**
         * Setter for upload.
         * @param  upload  Boolean value for upload.
         * @return Builder
         */
        public Builder upload(Boolean upload) {
            this.upload = upload;
            return this;
        }

        /**
         * Setter for user.
         * @param  user  String value for user.
         * @return Builder
         */
        public Builder user(String user) {
            this.user = user;
            return this;
        }

        /**
         * Setter for userProfile.
         * @param  userProfile  ObjsUserProfileShort value for userProfile.
         * @return Builder
         */
        public Builder userProfile(ObjsUserProfileShort userProfile) {
            this.userProfile = userProfile;
            return this;
        }

        /**
         * Setter for userTeam.
         * @param  userTeam  String value for userTeam.
         * @return Builder
         */
        public Builder userTeam(String userTeam) {
            this.userTeam = userTeam;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link MessageObject} object using the set fields.
         * @return {@link MessageObject}
         */
        public MessageObject build() {
            MessageObject model =
                    new MessageObject(text, ts, type, attachments, blocks, botId, botProfile,
                            clientMsgId, comment, displayAsBot, file, files, icons, inviter,
                            isDelayedMessage, isIntro, isStarred, lastRead, latestReply, name,
                            oldName, parentUserId, permalink, pinnedTo, purpose, reactions,
                            replyCount, replyUsers, replyUsersCount, sourceTeam, subscribed,
                            subtype, team, threadTs, topic, unreadCount, upload, user, userProfile,
                            userTeam, username);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
