/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Prefs1 type.
 */
public class Prefs1 {
    private CanThread canThread;
    private WhoCanPost whoCanPost;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Prefs1() {
    }

    /**
     * Initialization constructor.
     * @param  canThread  CanThread value for canThread.
     * @param  whoCanPost  WhoCanPost value for whoCanPost.
     */
    public Prefs1(
            CanThread canThread,
            WhoCanPost whoCanPost) {
        this.canThread = canThread;
        this.whoCanPost = whoCanPost;
    }

    /**
     * Getter for CanThread.
     * @return Returns the CanThread
     */
    @JsonGetter("can_thread")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CanThread getCanThread() {
        return canThread;
    }

    /**
     * Setter for CanThread.
     * @param canThread Value for CanThread
     */
    @JsonSetter("can_thread")
    public void setCanThread(CanThread canThread) {
        this.canThread = canThread;
    }

    /**
     * Getter for WhoCanPost.
     * @return Returns the WhoCanPost
     */
    @JsonGetter("who_can_post")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public WhoCanPost getWhoCanPost() {
        return whoCanPost;
    }

    /**
     * Setter for WhoCanPost.
     * @param whoCanPost Value for WhoCanPost
     */
    @JsonSetter("who_can_post")
    public void setWhoCanPost(WhoCanPost whoCanPost) {
        this.whoCanPost = whoCanPost;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Prefs1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Prefs1 [" + "canThread=" + canThread + ", whoCanPost=" + whoCanPost
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Prefs1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Prefs1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .canThread(getCanThread())
                .whoCanPost(getWhoCanPost());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Prefs1}.
     */
    public static class Builder {
        private CanThread canThread;
        private WhoCanPost whoCanPost;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for canThread.
         * @param  canThread  CanThread value for canThread.
         * @return Builder
         */
        public Builder canThread(CanThread canThread) {
            this.canThread = canThread;
            return this;
        }

        /**
         * Setter for whoCanPost.
         * @param  whoCanPost  WhoCanPost value for whoCanPost.
         * @return Builder
         */
        public Builder whoCanPost(WhoCanPost whoCanPost) {
            this.whoCanPost = whoCanPost;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Prefs1} object using the set fields.
         * @return {@link Prefs1}
         */
        public Prefs1 build() {
            Prefs1 model =
                    new Prefs1(canThread, whoCanPost);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
