/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Prefs type.
 */
public class Prefs {
    private List<String> channels;
    private List<String> groups;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Prefs() {
    }

    /**
     * Initialization constructor.
     * @param  channels  List of String value for channels.
     * @param  groups  List of String value for groups.
     */
    public Prefs(
            List<String> channels,
            List<String> groups) {
        this.channels = channels;
        this.groups = groups;
    }

    /**
     * Getter for Channels.
     * @return Returns the List of String
     */
    @JsonGetter("channels")
    public List<String> getChannels() {
        return channels;
    }

    /**
     * Setter for Channels.
     * @param channels Value for List of String
     */
    @JsonSetter("channels")
    public void setChannels(List<String> channels) {
        this.channels = channels;
    }

    /**
     * Getter for Groups.
     * @return Returns the List of String
     */
    @JsonGetter("groups")
    public List<String> getGroups() {
        return groups;
    }

    /**
     * Setter for Groups.
     * @param groups Value for List of String
     */
    @JsonSetter("groups")
    public void setGroups(List<String> groups) {
        this.groups = groups;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Prefs into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Prefs [" + "channels=" + channels + ", groups=" + groups + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Prefs.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Prefs.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(channels, groups);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Prefs}.
     */
    public static class Builder {
        private List<String> channels;
        private List<String> groups;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  channels  List of String value for channels.
         * @param  groups  List of String value for groups.
         */
        public Builder(List<String> channels, List<String> groups) {
            this.channels = channels;
            this.groups = groups;
        }

        /**
         * Setter for channels.
         * @param  channels  List of String value for channels.
         * @return Builder
         */
        public Builder channels(List<String> channels) {
            this.channels = channels;
            return this;
        }

        /**
         * Setter for groups.
         * @param  groups  List of String value for groups.
         * @return Builder
         */
        public Builder groups(List<String> groups) {
            this.groups = groups;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Prefs} object using the set fields.
         * @return {@link Prefs}
         */
        public Prefs build() {
            Prefs model =
                    new Prefs(channels, groups);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
