/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ReactionsListSchema type.
 */
public class ReactionsListSchema {
    private List<Object> items;
    private String ok;
    private PagingObject paging;
    private Object responseMetadata;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ReactionsListSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  items  List of Object value for items.
     * @param  ok  String value for ok.
     * @param  paging  PagingObject value for paging.
     * @param  responseMetadata  Object value for responseMetadata.
     */
    public ReactionsListSchema(
            List<Object> items,
            String ok,
            PagingObject paging,
            Object responseMetadata) {
        this.items = items;
        this.ok = ok;
        this.paging = paging;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Getter for Items.
     * @return Returns the List of Object
     */
    @JsonGetter("items")
    public List<Object> getItems() {
        return items;
    }

    /**
     * Setter for Items.
     * @param items Value for List of Object
     */
    @JsonSetter("items")
    public void setItems(List<Object> items) {
        this.items = items;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Paging.
     * @return Returns the PagingObject
     */
    @JsonGetter("paging")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PagingObject getPaging() {
        return paging;
    }

    /**
     * Setter for Paging.
     * @param paging Value for PagingObject
     */
    @JsonSetter("paging")
    public void setPaging(PagingObject paging) {
        this.paging = paging;
    }

    /**
     * Getter for ResponseMetadata.
     * @return Returns the Object
     */
    @JsonGetter("response_metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Setter for ResponseMetadata.
     * @param responseMetadata Value for Object
     */
    @JsonSetter("response_metadata")
    public void setResponseMetadata(Object responseMetadata) {
        this.responseMetadata = responseMetadata;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ReactionsListSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReactionsListSchema [" + "items=" + items + ", ok=" + ok + ", paging=" + paging
                + ", responseMetadata=" + responseMetadata + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ReactionsListSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReactionsListSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(items, ok)
                .paging(getPaging())
                .responseMetadata(getResponseMetadata());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ReactionsListSchema}.
     */
    public static class Builder {
        private List<Object> items;
        private String ok = "True";
        private PagingObject paging;
        private Object responseMetadata;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  items  List of Object value for items.
         * @param  ok  String value for ok.
         */
        public Builder(List<Object> items, String ok) {
            this.items = items;
            this.ok = ok;
        }

        /**
         * Setter for items.
         * @param  items  List of Object value for items.
         * @return Builder
         */
        public Builder items(List<Object> items) {
            this.items = items;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for paging.
         * @param  paging  PagingObject value for paging.
         * @return Builder
         */
        public Builder paging(PagingObject paging) {
            this.paging = paging;
            return this;
        }

        /**
         * Setter for responseMetadata.
         * @param  responseMetadata  Object value for responseMetadata.
         * @return Builder
         */
        public Builder responseMetadata(Object responseMetadata) {
            this.responseMetadata = responseMetadata;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ReactionsListSchema} object using the set fields.
         * @return {@link ReactionsListSchema}
         */
        public ReactionsListSchema build() {
            ReactionsListSchema model =
                    new ReactionsListSchema(items, ok, paging, responseMetadata);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
