/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for UsergroupsUsersListSchema type.
 */
public class UsergroupsUsersListSchema {
    private String ok;
    private List<String> users;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UsergroupsUsersListSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  ok  String value for ok.
     * @param  users  List of String value for users.
     */
    public UsergroupsUsersListSchema(
            String ok,
            List<String> users) {
        this.ok = ok;
        this.users = users;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for Users.
     * @return Returns the List of String
     */
    @JsonGetter("users")
    public List<String> getUsers() {
        return users;
    }

    /**
     * Setter for Users.
     * @param users Value for List of String
     */
    @JsonSetter("users")
    public void setUsers(List<String> users) {
        this.users = users;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UsergroupsUsersListSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsergroupsUsersListSchema [" + "ok=" + ok + ", users=" + users
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UsergroupsUsersListSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UsergroupsUsersListSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ok, users);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UsergroupsUsersListSchema}.
     */
    public static class Builder {
        private String ok = "True";
        private List<String> users;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ok  String value for ok.
         * @param  users  List of String value for users.
         */
        public Builder(String ok, List<String> users) {
            this.ok = ok;
            this.users = users;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for users.
         * @param  users  List of String value for users.
         * @return Builder
         */
        public Builder users(List<String> users) {
            this.users = users;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UsergroupsUsersListSchema} object using the set fields.
         * @return {@link UsergroupsUsersListSchema}
         */
        public UsergroupsUsersListSchema build() {
            UsergroupsUsersListSchema model =
                    new UsergroupsUsersListSchema(ok, users);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
