/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for UsersListSchema type.
 */
public class UsersListSchema {
    private int cacheTs;
    private List<Object> members;
    private String ok;
    private Object responseMetadata;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UsersListSchema() {
        ok = "True";
    }

    /**
     * Initialization constructor.
     * @param  cacheTs  int value for cacheTs.
     * @param  members  List of Object value for members.
     * @param  ok  String value for ok.
     * @param  responseMetadata  Object value for responseMetadata.
     */
    public UsersListSchema(
            int cacheTs,
            List<Object> members,
            String ok,
            Object responseMetadata) {
        this.cacheTs = cacheTs;
        this.members = members;
        this.ok = ok;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Getter for CacheTs.
     * @return Returns the int
     */
    @JsonGetter("cache_ts")
    public int getCacheTs() {
        return cacheTs;
    }

    /**
     * Setter for CacheTs.
     * @param cacheTs Value for int
     */
    @JsonSetter("cache_ts")
    public void setCacheTs(int cacheTs) {
        this.cacheTs = cacheTs;
    }

    /**
     * Getter for Members.
     * @return Returns the List of Object
     */
    @JsonGetter("members")
    public List<Object> getMembers() {
        return members;
    }

    /**
     * Setter for Members.
     * @param members Value for List of Object
     */
    @JsonSetter("members")
    public void setMembers(List<Object> members) {
        this.members = members;
    }

    /**
     * Getter for Ok.
     * @return Returns the String
     */
    @JsonGetter("ok")
    public String getOk() {
        return ok;
    }

    /**
     * Setter for Ok.
     * @param ok Value for String
     */
    @JsonSetter("ok")
    private void setOk(String ok) {
        this.ok = ok;
    }

    /**
     * Getter for ResponseMetadata.
     * @return Returns the Object
     */
    @JsonGetter("response_metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Setter for ResponseMetadata.
     * @param responseMetadata Value for Object
     */
    @JsonSetter("response_metadata")
    public void setResponseMetadata(Object responseMetadata) {
        this.responseMetadata = responseMetadata;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UsersListSchema into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsersListSchema [" + "cacheTs=" + cacheTs + ", members=" + members + ", ok=" + ok
                + ", responseMetadata=" + responseMetadata + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UsersListSchema.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UsersListSchema.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(cacheTs, members, ok)
                .responseMetadata(getResponseMetadata());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UsersListSchema}.
     */
    public static class Builder {
        private int cacheTs;
        private List<Object> members;
        private String ok = "True";
        private Object responseMetadata;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  cacheTs  int value for cacheTs.
         * @param  members  List of Object value for members.
         * @param  ok  String value for ok.
         */
        public Builder(int cacheTs, List<Object> members, String ok) {
            this.cacheTs = cacheTs;
            this.members = members;
            this.ok = ok;
        }

        /**
         * Setter for cacheTs.
         * @param  cacheTs  int value for cacheTs.
         * @return Builder
         */
        public Builder cacheTs(int cacheTs) {
            this.cacheTs = cacheTs;
            return this;
        }

        /**
         * Setter for members.
         * @param  members  List of Object value for members.
         * @return Builder
         */
        public Builder members(List<Object> members) {
            this.members = members;
            return this;
        }

        /**
         * Setter for ok.
         * @param  ok  String value for ok.
         * @return Builder
         */
        public Builder ok(String ok) {
            this.ok = ok;
            return this;
        }

        /**
         * Setter for responseMetadata.
         * @param  responseMetadata  Object value for responseMetadata.
         * @return Builder
         */
        public Builder responseMetadata(Object responseMetadata) {
            this.responseMetadata = responseMetadata;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UsersListSchema} object using the set fields.
         * @return {@link UsersListSchema}
         */
        public UsersListSchema build() {
            UsersListSchema model =
                    new UsersListSchema(cacheTs, members, ok, responseMetadata);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
