/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.controllers;

import com.slack.ApiHelper;
import com.slack.Server;
import com.slack.exceptions.ApiException;
import com.slack.exceptions.DefaultErrorTemplateException;
import com.slack.http.request.HttpMethod;
import com.slack.http.response.ApiResponse;
import com.slack.models.DefaultSuccessTemplate;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AdminTeamsOwnersController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public AdminTeamsOwnersController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * List all of the owners on a given workspace.
     * @param  token  Required parameter: Authentication token. Requires scope: `admin.teams:read`
     * @param  teamId  Required parameter:
     * @param  limit  Optional parameter: The maximum number of items to return. Must be between 1 -
     *         1000 both inclusive.
     * @param  cursor  Optional parameter: Set `cursor` to `next_cursor` returned by the previous
     *         call to list items in the next page.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DefaultSuccessTemplate> adminTeamsOwnersList(
            final String token,
            final String teamId,
            final Integer limit,
            final String cursor) throws ApiException, IOException {
        return prepareAdminTeamsOwnersListRequest(token, teamId, limit, cursor).execute();
    }

    /**
     * List all of the owners on a given workspace.
     * @param  token  Required parameter: Authentication token. Requires scope: `admin.teams:read`
     * @param  teamId  Required parameter:
     * @param  limit  Optional parameter: The maximum number of items to return. Must be between 1 -
     *         1000 both inclusive.
     * @param  cursor  Optional parameter: Set `cursor` to `next_cursor` returned by the previous
     *         call to list items in the next page.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DefaultSuccessTemplate>> adminTeamsOwnersListAsync(
            final String token,
            final String teamId,
            final Integer limit,
            final String cursor) {
        try {
            return prepareAdminTeamsOwnersListRequest(token, teamId, limit, cursor).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for adminTeamsOwnersList.
     */
    private ApiCall<ApiResponse<DefaultSuccessTemplate>, ApiException> prepareAdminTeamsOwnersListRequest(
            final String token,
            final String teamId,
            final Integer limit,
            final String cursor) {
        return new ApiCall.Builder<ApiResponse<DefaultSuccessTemplate>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/admin.teams.owners.list")
                        .queryParam(param -> param.key("token")
                                .value(token))
                        .queryParam(param -> param.key("team_id")
                                .value(teamId))
                        .queryParam(param -> param.key("limit")
                                .value(limit).isRequired(false))
                        .queryParam(param -> param.key("cursor")
                                .value(cursor).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DefaultSuccessTemplate.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response",
                                (reason, context) -> new DefaultErrorTemplateException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}