/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.controllers;

import com.slack.ApiHelper;
import com.slack.Server;
import com.slack.exceptions.ApiException;
import com.slack.exceptions.BotsInfoErrorSchemaException;
import com.slack.http.request.HttpMethod;
import com.slack.http.response.ApiResponse;
import com.slack.models.BotsInfoSchema;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class BotsController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public BotsController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Gets information about a bot user.
     * @param  token  Required parameter: Authentication token. Requires scope: `users:read`
     * @param  bot  Optional parameter: Bot user to get info on
     * @return    Returns the BotsInfoSchema wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<BotsInfoSchema> botsInfo(
            final String token,
            final String bot) throws ApiException, IOException {
        return prepareBotsInfoRequest(token, bot).execute();
    }

    /**
     * Gets information about a bot user.
     * @param  token  Required parameter: Authentication token. Requires scope: `users:read`
     * @param  bot  Optional parameter: Bot user to get info on
     * @return    Returns the BotsInfoSchema wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<BotsInfoSchema>> botsInfoAsync(
            final String token,
            final String bot) {
        try {
            return prepareBotsInfoRequest(token, bot).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for botsInfo.
     */
    private ApiCall<ApiResponse<BotsInfoSchema>, ApiException> prepareBotsInfoRequest(
            final String token,
            final String bot) {
        return new ApiCall.Builder<ApiResponse<BotsInfoSchema>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/bots.info")
                        .queryParam(param -> param.key("token")
                                .value(token))
                        .queryParam(param -> param.key("bot")
                                .value(bot).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, BotsInfoSchema.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("When no bot can be found, it returns an error.",
                                (reason, context) -> new BotsInfoErrorSchemaException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}