/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.controllers;

import com.slack.ApiHelper;
import com.slack.Server;
import com.slack.exceptions.ApiException;
import com.slack.exceptions.UsersProfileGetErrorSchemaException;
import com.slack.exceptions.UsersProfileSetErrorSchemaException;
import com.slack.http.request.HttpMethod;
import com.slack.http.response.ApiResponse;
import com.slack.models.UsersProfileGetSchema;
import com.slack.models.UsersProfileSetSchema;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class UsersProfileController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public UsersProfileController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Retrieves a user's profile information.
     * @param  token  Required parameter: Authentication token. Requires scope: `users.profile:read`
     * @param  includeLabels  Optional parameter: Include labels for each ID in custom profile
     *         fields
     * @param  user  Optional parameter: User to retrieve profile info for
     * @return    Returns the UsersProfileGetSchema wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<UsersProfileGetSchema> usersProfileGet(
            final String token,
            final Boolean includeLabels,
            final String user) throws ApiException, IOException {
        return prepareUsersProfileGetRequest(token, includeLabels, user).execute();
    }

    /**
     * Retrieves a user's profile information.
     * @param  token  Required parameter: Authentication token. Requires scope: `users.profile:read`
     * @param  includeLabels  Optional parameter: Include labels for each ID in custom profile
     *         fields
     * @param  user  Optional parameter: User to retrieve profile info for
     * @return    Returns the UsersProfileGetSchema wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<UsersProfileGetSchema>> usersProfileGetAsync(
            final String token,
            final Boolean includeLabels,
            final String user) {
        try {
            return prepareUsersProfileGetRequest(token, includeLabels, user).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for usersProfileGet.
     */
    private ApiCall<ApiResponse<UsersProfileGetSchema>, ApiException> prepareUsersProfileGetRequest(
            final String token,
            final Boolean includeLabels,
            final String user) {
        return new ApiCall.Builder<ApiResponse<UsersProfileGetSchema>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/users.profile.get")
                        .queryParam(param -> param.key("token")
                                .value(token))
                        .queryParam(param -> param.key("include_labels")
                                .value(includeLabels).isRequired(false))
                        .queryParam(param -> param.key("user")
                                .value(user).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, UsersProfileGetSchema.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response",
                                (reason, context) -> new UsersProfileGetErrorSchemaException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Set the profile information for a user.
     * @param  token  Required parameter: Authentication token. Requires scope:
     *         `users.profile:write`
     * @param  name  Optional parameter: Name of a single key to set. Usable only if `profile` is
     *         not passed.
     * @param  profile  Optional parameter: Collection of key:value pairs presented as a URL-encoded
     *         JSON hash. At most 50 fields may be set. Each field name is limited to 255
     *         characters.
     * @param  user  Optional parameter: ID of user to change. This argument may only be specified
     *         by team admins on paid teams.
     * @param  value  Optional parameter: Value to set a single key to. Usable only if `profile` is
     *         not passed.
     * @return    Returns the UsersProfileSetSchema wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<UsersProfileSetSchema> usersProfileSet(
            final String token,
            final String name,
            final String profile,
            final String user,
            final String value) throws ApiException, IOException {
        return prepareUsersProfileSetRequest(token, name, profile, user, value).execute();
    }

    /**
     * Set the profile information for a user.
     * @param  token  Required parameter: Authentication token. Requires scope:
     *         `users.profile:write`
     * @param  name  Optional parameter: Name of a single key to set. Usable only if `profile` is
     *         not passed.
     * @param  profile  Optional parameter: Collection of key:value pairs presented as a URL-encoded
     *         JSON hash. At most 50 fields may be set. Each field name is limited to 255
     *         characters.
     * @param  user  Optional parameter: ID of user to change. This argument may only be specified
     *         by team admins on paid teams.
     * @param  value  Optional parameter: Value to set a single key to. Usable only if `profile` is
     *         not passed.
     * @return    Returns the UsersProfileSetSchema wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<UsersProfileSetSchema>> usersProfileSetAsync(
            final String token,
            final String name,
            final String profile,
            final String user,
            final String value) {
        try {
            return prepareUsersProfileSetRequest(token, name, profile, user, value).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for usersProfileSet.
     */
    private ApiCall<ApiResponse<UsersProfileSetSchema>, ApiException> prepareUsersProfileSetRequest(
            final String token,
            final String name,
            final String profile,
            final String user,
            final String value) {
        return new ApiCall.Builder<ApiResponse<UsersProfileSetSchema>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/users.profile.set")
                        .formParam(param -> param.key("name")
                                .value(name).isRequired(false))
                        .formParam(param -> param.key("profile")
                                .value(profile).isRequired(false))
                        .formParam(param -> param.key("user")
                                .value(user).isRequired(false))
                        .formParam(param -> param.key("value")
                                .value(value).isRequired(false))
                        .headerParam(param -> param.key("token")
                                .value(token).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, UsersProfileSetSchema.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response",
                                (reason, context) -> new UsersProfileSetErrorSchemaException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}