/*
 * SlackWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.slack.controllers;

import com.slack.ApiHelper;
import com.slack.Server;
import com.slack.exceptions.ApiException;
import com.slack.exceptions.DefaultErrorTemplateException;
import com.slack.http.request.HttpMethod;
import com.slack.http.response.ApiResponse;
import com.slack.models.DefaultSuccessTemplate;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class ViewsController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public ViewsController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Open a view for a user.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  triggerId  Required parameter: Exchange a trigger to post to the user.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DefaultSuccessTemplate> viewsOpen(
            final String token,
            final String triggerId,
            final String view) throws ApiException, IOException {
        return prepareViewsOpenRequest(token, triggerId, view).execute();
    }

    /**
     * Open a view for a user.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  triggerId  Required parameter: Exchange a trigger to post to the user.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DefaultSuccessTemplate>> viewsOpenAsync(
            final String token,
            final String triggerId,
            final String view) {
        try {
            return prepareViewsOpenRequest(token, triggerId, view).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for viewsOpen.
     */
    private ApiCall<ApiResponse<DefaultSuccessTemplate>, ApiException> prepareViewsOpenRequest(
            final String token,
            final String triggerId,
            final String view) {
        return new ApiCall.Builder<ApiResponse<DefaultSuccessTemplate>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/views.open")
                        .queryParam(param -> param.key("trigger_id")
                                .value(triggerId))
                        .queryParam(param -> param.key("view")
                                .value(view))
                        .headerParam(param -> param.key("token")
                                .value(token).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DefaultSuccessTemplate.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response, before getting to any possible validation errors.",
                                (reason, context) -> new DefaultErrorTemplateException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Publish a static view for a User.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  userId  Required parameter: `id` of the user you want publish a view to.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @param  hash  Optional parameter: A string that represents view state to protect against
     *         possible race conditions.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DefaultSuccessTemplate> viewsPublish(
            final String token,
            final String userId,
            final String view,
            final String hash) throws ApiException, IOException {
        return prepareViewsPublishRequest(token, userId, view, hash).execute();
    }

    /**
     * Publish a static view for a User.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  userId  Required parameter: `id` of the user you want publish a view to.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @param  hash  Optional parameter: A string that represents view state to protect against
     *         possible race conditions.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DefaultSuccessTemplate>> viewsPublishAsync(
            final String token,
            final String userId,
            final String view,
            final String hash) {
        try {
            return prepareViewsPublishRequest(token, userId, view, hash).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for viewsPublish.
     */
    private ApiCall<ApiResponse<DefaultSuccessTemplate>, ApiException> prepareViewsPublishRequest(
            final String token,
            final String userId,
            final String view,
            final String hash) {
        return new ApiCall.Builder<ApiResponse<DefaultSuccessTemplate>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/views.publish")
                        .queryParam(param -> param.key("user_id")
                                .value(userId))
                        .queryParam(param -> param.key("view")
                                .value(view))
                        .queryParam(param -> param.key("hash")
                                .value(hash).isRequired(false))
                        .headerParam(param -> param.key("token")
                                .value(token).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DefaultSuccessTemplate.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response, before getting to any possible validation errors.",
                                (reason, context) -> new DefaultErrorTemplateException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Push a view onto the stack of a root view.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  triggerId  Required parameter: Exchange a trigger to post to the user.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DefaultSuccessTemplate> viewsPush(
            final String token,
            final String triggerId,
            final String view) throws ApiException, IOException {
        return prepareViewsPushRequest(token, triggerId, view).execute();
    }

    /**
     * Push a view onto the stack of a root view.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  triggerId  Required parameter: Exchange a trigger to post to the user.
     * @param  view  Required parameter: A [view payload](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DefaultSuccessTemplate>> viewsPushAsync(
            final String token,
            final String triggerId,
            final String view) {
        try {
            return prepareViewsPushRequest(token, triggerId, view).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for viewsPush.
     */
    private ApiCall<ApiResponse<DefaultSuccessTemplate>, ApiException> prepareViewsPushRequest(
            final String token,
            final String triggerId,
            final String view) {
        return new ApiCall.Builder<ApiResponse<DefaultSuccessTemplate>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/views.push")
                        .queryParam(param -> param.key("trigger_id")
                                .value(triggerId))
                        .queryParam(param -> param.key("view")
                                .value(view))
                        .headerParam(param -> param.key("token")
                                .value(token).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DefaultSuccessTemplate.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response.",
                                (reason, context) -> new DefaultErrorTemplateException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Update an existing view.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  viewId  Optional parameter: A unique identifier of the view to be updated. Either
     *         `view_id` or `external_id` is required.
     * @param  externalId  Optional parameter: A unique identifier of the view set by the developer.
     *         Must be unique for all views on a team. Max length of 255 characters. Either
     *         `view_id` or `external_id` is required.
     * @param  view  Optional parameter: A [view object](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @param  hash  Optional parameter: A string that represents view state to protect against
     *         possible race conditions.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<DefaultSuccessTemplate> viewsUpdate(
            final String token,
            final String viewId,
            final String externalId,
            final String view,
            final String hash) throws ApiException, IOException {
        return prepareViewsUpdateRequest(token, viewId, externalId, view, hash).execute();
    }

    /**
     * Update an existing view.
     * @param  token  Required parameter: Authentication token. Requires scope: `none`
     * @param  viewId  Optional parameter: A unique identifier of the view to be updated. Either
     *         `view_id` or `external_id` is required.
     * @param  externalId  Optional parameter: A unique identifier of the view set by the developer.
     *         Must be unique for all views on a team. Max length of 255 characters. Either
     *         `view_id` or `external_id` is required.
     * @param  view  Optional parameter: A [view object](/reference/surfaces/views). This must be a
     *         JSON-encoded string.
     * @param  hash  Optional parameter: A string that represents view state to protect against
     *         possible race conditions.
     * @return    Returns the DefaultSuccessTemplate wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<DefaultSuccessTemplate>> viewsUpdateAsync(
            final String token,
            final String viewId,
            final String externalId,
            final String view,
            final String hash) {
        try {
            return prepareViewsUpdateRequest(token, viewId, externalId, view, hash).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for viewsUpdate.
     */
    private ApiCall<ApiResponse<DefaultSuccessTemplate>, ApiException> prepareViewsUpdateRequest(
            final String token,
            final String viewId,
            final String externalId,
            final String view,
            final String hash) {
        return new ApiCall.Builder<ApiResponse<DefaultSuccessTemplate>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/views.update")
                        .queryParam(param -> param.key("view_id")
                                .value(viewId).isRequired(false))
                        .queryParam(param -> param.key("external_id")
                                .value(externalId).isRequired(false))
                        .queryParam(param -> param.key("view")
                                .value(view).isRequired(false))
                        .queryParam(param -> param.key("hash")
                                .value(hash).isRequired(false))
                        .headerParam(param -> param.key("token")
                                .value(token).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/x-www-form-urlencoded").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("slackAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, DefaultSuccessTemplate.class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Typical error response.",
                                (reason, context) -> new DefaultErrorTemplateException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}